#!/usr/bin/env python3
"""Exact SO(9)-equivariance gate for the certified temporal retract.

The sixteen Garden colors and the physical gauginos both carry the real
16-dimensional Spin(9) spinor action generated by S_ij = gamma_i gamma_j / 2.
This script constructs the induced action on the full 128|128 Garden module,
verifies its covariance exactly, proves that its skew lift is unique, and tests
whether the fixed J_B and P_F maps in the quotient witness are intertwiners.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np


def dense_signed_perm(perm: list[int], sign: list[int]) -> np.ndarray:
    out = np.zeros((len(perm), len(perm)), dtype=np.int64)
    out[np.arange(len(perm)), np.asarray(perm)] = np.asarray(sign)
    return out


def inverse_signed_perm(
    perm: list[int], sign: list[int]
) -> tuple[list[int], list[int]]:
    inverse_perm = [0] * len(perm)
    inverse_sign = [0] * len(perm)
    for row, column in enumerate(perm):
        inverse_perm[column] = row
        inverse_sign[column] = sign[row]
    return inverse_perm, inverse_sign


def multiply_signed_perm(
    left_perm: list[int],
    left_sign: list[int],
    right_perm: list[int],
    right_sign: list[int],
) -> tuple[list[int], list[int]]:
    perm = [right_perm[left_perm[row]] for row in range(len(left_perm))]
    sign = [
        left_sign[row] * right_sign[left_perm[row]]
        for row in range(len(left_perm))
    ]
    return perm, sign


class SignedDsu:
    def __init__(self, size: int) -> None:
        self.parent = list(range(size))
        self.relation = [1] * size
        self.consistent = [True] * size

    def find(self, item: int) -> tuple[int, int]:
        parent = self.parent[item]
        if parent != item:
            root, sign = self.find(parent)
            self.relation[item] *= sign
            self.parent[item] = root
        return self.parent[item], self.relation[item]

    def union(self, left: int, right: int, relation: int) -> None:
        left_root, left_sign = self.find(left)
        right_root, right_sign = self.find(right)
        if left_root == right_root:
            if left_sign != relation * right_sign:
                self.consistent[left_root] = False
            return
        self.parent[left_root] = right_root
        self.relation[left_root] = left_sign * relation * right_sign
        self.consistent[right_root] = (
            self.consistent[left_root] and self.consistent[right_root]
        )


def homogeneous_pair_dimension(
    l_perm: list[list[int]], l_sign: list[list[int]]
) -> int:
    """Dimension of C_B L_a = L_a C_F for every color a, exactly."""
    dimension = len(l_perm[0])
    inverse0_perm, inverse0_sign = inverse_signed_perm(l_perm[0], l_sign[0])
    relative = [
        multiply_signed_perm(
            l_perm[color], l_sign[color], inverse0_perm, inverse0_sign
        )
        for color in range(1, len(l_perm))
    ]
    dsu = SignedDsu(dimension * dimension)
    for perm, sign in relative:
        for row in range(dimension):
            mapped_row = perm[row]
            for column in range(dimension):
                mapped_column = perm[column]
                dsu.union(
                    row * dimension + column,
                    mapped_row * dimension + mapped_column,
                    sign[row] * sign[column],
                )
    roots: set[int] = set()
    for cell in range(dimension * dimension):
        root, _ = dsu.find(cell)
        if dsu.consistent[root]:
            roots.add(root)
    return len(roots)


def residual_summary(blocks: list[np.ndarray], scale: int) -> dict[str, int | bool]:
    maximum = max(int(np.max(np.abs(block))) for block in blocks)
    nonzero = sum(int(np.count_nonzero(block)) for block in blocks)
    failing = sum(int(np.count_nonzero(block) > 0) for block in blocks)
    return {
        "scale": scale,
        "maximum_scaled_residual": maximum,
        "nonzero_scaled_entries": nonzero,
        "failing_generators": failing,
        "exactly_zero": maximum == 0,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", nargs="?", default="results/sr_hole_minimal.json")
    parser.add_argument(
        "--candidate", default="results/sr_joint_section_candidate.npz"
    )
    parser.add_argument("--output", default="results/sr_so9_equivariance_audit.json")
    args = parser.parse_args()

    report = json.loads(Path(args.input).read_text())
    topology = next(
        item
        for item in report["topologies"]
        if item["auxiliary_projection"].get("witness")
    )
    witness = topology["auxiliary_projection"]["witness"]
    data = witness["joint_section_data"]
    l_perm = data["l_perm"]
    l_sign = data["l_sign"]
    gamma_perm = data["gamma_perm"]
    gamma_sign = data["gamma_sign"]
    full_l = [
        dense_signed_perm(perm, sign) for perm, sign in zip(l_perm, l_sign)
    ]
    gamma = [
        dense_signed_perm(perm, sign)
        for perm, sign in zip(gamma_perm, gamma_sign)
    ]

    # G_alpha has a spatial-vector row and a physical-gaugino column.
    physical_linkage = [
        np.stack([gamma[vector][charge, :] for vector in range(9)], axis=0)
        for charge in range(16)
    ]

    fermion_projection = np.zeros((16, 128), dtype=np.int64)
    for entry in witness["projection"]:
        fermion_projection[entry["physical_beta"], entry["full_fermion"]] = entry[
            "sign"
        ]
    boson_injection = np.zeros((128, 9), dtype=np.int64)
    for vector, full_boson in enumerate(witness["boson_by_vector"]):
        boson_injection[full_boson, vector] = 1

    full_covariance = []
    physical_covariance = []
    full_boson_skew = []
    full_fermion_skew = []
    boson_injection_intertwiner = []
    fermion_projection_intertwiner = []
    candidate_boson_projection_intertwiner = []
    candidate_fermion_section_intertwiner = []
    labels: list[tuple[int, int]] = []
    spin2_generators: list[np.ndarray] = []
    vector_generators: list[np.ndarray] = []
    boson4_generators: list[np.ndarray] = []
    fermion4_generators: list[np.ndarray] = []
    candidate = np.load(args.candidate)
    boson_projection = np.asarray(candidate["boson_projection"], dtype=np.float64)
    fermion_section = np.asarray(candidate["fermion_section"], dtype=np.float64)

    # S2 = 2 S_ij = gamma_i gamma_j.  The induced full generators have
    # denominator four, so B4 = 4 B and F4 = 4 F are exact integer matrices.
    for i in range(9):
        for j in range(i + 1, 9):
            spin2 = gamma[i] @ gamma[j]
            vector = np.zeros((9, 9), dtype=np.int64)
            vector[i, j] = 1
            vector[j, i] = -1

            boson4 = np.zeros((128, 128), dtype=np.int64)
            fermion4 = np.zeros((128, 128), dtype=np.int64)
            for alpha in range(16):
                for beta in range(alpha + 1, 16):
                    coefficient = int(spin2[alpha, beta])
                    if coefficient == 0:
                        continue
                    boson4 += coefficient * (full_l[alpha] @ full_l[beta].T)
                    fermion4 += coefficient * (full_l[alpha].T @ full_l[beta])

            labels.append((i, j))
            spin2_generators.append(spin2)
            vector_generators.append(vector)
            boson4_generators.append(boson4)
            fermion4_generators.append(fermion4)

            full_boson_skew.append(boson4 + boson4.T)
            full_fermion_skew.append(fermion4 + fermion4.T)
            for alpha in range(16):
                color_term = sum(
                    int(spin2[alpha, beta]) * full_l[beta]
                    for beta in range(16)
                )
                # 4(B L - L F + S_color L) = 0 because S_color=spin2/2.
                full_covariance.append(
                    boson4 @ full_l[alpha]
                    - full_l[alpha] @ fermion4
                    + 2 * color_term
                )
                physical_color_term = sum(
                    int(spin2[alpha, beta]) * physical_linkage[beta]
                    for beta in range(16)
                )
                # 2(V G - G S + S_color G) = 0.
                physical_covariance.append(
                    2 * vector @ physical_linkage[alpha]
                    - physical_linkage[alpha] @ spin2
                    + physical_color_term
                )

            boson_injection_intertwiner.append(
                boson4 @ boson_injection - 4 * boson_injection @ vector
            )
            fermion_projection_intertwiner.append(
                fermion_projection @ fermion4
                - 2 * spin2 @ fermion_projection
            )
            candidate_boson_projection_intertwiner.append(
                boson_projection @ boson4 - 4 * vector @ boson_projection
            )
            candidate_fermion_section_intertwiner.append(
                fermion4 @ fermion_section - 2 * fermion_section @ spin2
            )

    # Verify the same so(9) structure constants on the physical spinor and both
    # full field spaces. The physical vector commutator supplies the exact
    # integer coefficients in the standard M_ij basis.
    spin_closure = []
    boson_closure = []
    fermion_closure = []
    for left in range(len(labels)):
        for right in range(left + 1, len(labels)):
            vector_commutator = (
                vector_generators[left] @ vector_generators[right]
                - vector_generators[right] @ vector_generators[left]
            )
            coefficients = [
                int(vector_commutator[i, j]) for i, j in labels
            ]
            expected_spin2 = sum(
                coefficient * generator
                for coefficient, generator in zip(coefficients, spin2_generators)
            )
            expected_boson4 = sum(
                coefficient * generator
                for coefficient, generator in zip(coefficients, boson4_generators)
            )
            expected_fermion4 = sum(
                coefficient * generator
                for coefficient, generator in zip(coefficients, fermion4_generators)
            )
            spin_closure.append(
                spin2_generators[left] @ spin2_generators[right]
                - spin2_generators[right] @ spin2_generators[left]
                - 2 * expected_spin2
            )
            boson_closure.append(
                boson4_generators[left] @ boson4_generators[right]
                - boson4_generators[right] @ boson4_generators[left]
                - 4 * expected_boson4
            )
            fermion_closure.append(
                fermion4_generators[left] @ fermion4_generators[right]
                - fermion4_generators[right] @ fermion4_generators[left]
                - 4 * expected_fermion4
            )

    pair_dimension = homogeneous_pair_dimension(l_perm, l_sign)
    # The identity pair is always homogeneous. Dimension one therefore means
    # that it spans the entire homogeneous solution space. It is symmetric, so
    # it contributes no freedom to a skew Lie-algebra generator.
    unique_skew_lift = pair_dimension == 1

    identity9 = np.eye(9, dtype=np.int64)
    identity16 = np.eye(16, dtype=np.int64)
    identity128 = np.eye(128, dtype=np.int64)
    physical_vector_casimir = -sum(
        generator @ generator for generator in vector_generators
    )
    physical_spinor_casimir4 = -sum(
        generator @ generator for generator in spin2_generators
    )
    full_boson_casimir16 = -sum(
        generator @ generator for generator in boson4_generators
    )
    full_fermion_casimir16 = -sum(
        generator @ generator for generator in fermion4_generators
    )
    casimir_checks = {
        "physical_vector": residual_summary(
            [physical_vector_casimir - 8 * identity9], 1
        ),
        "physical_spinor_scaled_by_4": residual_summary(
            [physical_spinor_casimir4 - 36 * identity16], 4
        ),
        "full_bosons_scaled_by_16": residual_summary(
            [full_boson_casimir16 - 288 * identity128], 16
        ),
        "full_fermions_scaled_by_16": residual_summary(
            [full_fermion_casimir16 - 288 * identity128], 16
        ),
    }
    assert all(check["exactly_zero"] for check in casimir_checks.values())
    casimir_eigenvalues = {
        "physical_vector": 8,
        "physical_spinor": 9,
        "full_bosons": 18,
        "full_fermions": 18,
    }
    # If T intertwines two representations, their quadratic Casimirs obey
    # C_target T = T C_source. Distinct scalar eigenvalues force T=0.
    casimir_forces_all_retract_maps_zero = (
        casimir_eigenvalues["physical_vector"]
        != casimir_eigenvalues["full_bosons"]
        and casimir_eigenvalues["physical_spinor"]
        != casimir_eigenvalues["full_fermions"]
    )

    exact_checks = {
        "full_garden_so9_covariance": residual_summary(full_covariance, 4),
        "physical_seed_so9_covariance": residual_summary(physical_covariance, 2),
        "full_boson_generators_skew": residual_summary(full_boson_skew, 4),
        "full_fermion_generators_skew": residual_summary(full_fermion_skew, 4),
        "physical_spinor_so9_closure": residual_summary(spin_closure, 4),
        "full_boson_so9_closure": residual_summary(boson_closure, 16),
        "full_fermion_so9_closure": residual_summary(fermion_closure, 16),
        "fixed_boson_injection_intertwines": residual_summary(
            boson_injection_intertwiner, 4
        ),
        "fixed_fermion_projection_intertwines": residual_summary(
            fermion_projection_intertwiner, 4
        ),
    }
    candidate_checks = {
        "boson_projection_maximum_residual": float(
            max(np.max(np.abs(block)) for block in candidate_boson_projection_intertwiner)
            / 4.0
        ),
        "fermion_section_maximum_residual": float(
            max(np.max(np.abs(block)) for block in candidate_fermion_section_intertwiner)
            / 4.0
        ),
    }
    fixed_retract_equivariant = (
        exact_checks["fixed_boson_injection_intertwines"]["exactly_zero"]
        and exact_checks["fixed_fermion_projection_intertwines"]["exactly_zero"]
    )
    output = {
        "source": args.input,
        "candidate": args.candidate,
        "input_sha256": hashlib.sha256(Path(args.input).read_bytes()).hexdigest(),
        "candidate_sha256": hashlib.sha256(Path(args.candidate).read_bytes()).hexdigest(),
        "catalog_index": topology["catalog_index"],
        "dashing_index": witness["dashing_index"],
        "rotation_generators": 36,
        "homogeneous_covariant_pair_dimension": pair_dimension,
        "unique_skew_field_action_lift": unique_skew_lift,
        "exact_checks": exact_checks,
        "quadratic_casimir_checks": casimir_checks,
        "quadratic_casimir_eigenvalues": casimir_eigenvalues,
        "casimir_forces_all_so9_retract_maps_zero": (
            casimir_forces_all_retract_maps_zero
        ),
        "stored_dense_candidate_checks": candidate_checks,
        "fixed_retract_so9_equivariant": fixed_retract_equivariant,
        "conclusion": (
            "No nonzero SO(9)-equivariant retract maps exist for this valise "
            "Garden module: the full boson and fermion spaces have quadratic "
            "Casimir 18, while the physical vector and spinor have Casimirs 8 "
            "and 9. The fixed witness fails explicitly, and the Casimir mismatch "
            "excludes every alternative choice of J_B, P_B, J_F, and P_F under "
            "the unique skew field-action lift."
            if casimir_forces_all_retract_maps_zero
            else (
                "The fixed J_B/P_F quotient witness is not SO(9)-equivariant, "
                "but the Casimir audit did not exclude every alternative map."
            )
        ),
    }
    Path(args.output).write_text(json.dumps(output, indent=2) + "\n")
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
