#![allow(dead_code)]

//! Exact nonabelian component closure for the nine BBBM supersymmetries.
//!
//! The source is `twisted10df.tex` from the arXiv:0705.2002 source archive
//! (SHA-256 `499b0ad8ec07da5bded479070814950f65ff8c5e2f7479e647aa77c8ee7d637c`).
//! The functions `delta` below transcribe Eqs. (22) and (23), including the
//! field redefinition printed immediately before Eq. (22). The closure targets
//! are Eq. (24). No equation of motion, trace cyclicity, integration by parts,
//! or numerical matrix sample is used.
//!
//! We work in the free associative differential superalgebra generated by the
//! component fields. A monomial is an ordered word of field jets. Ordinary
//! derivatives are even derivations and each supersymmetry generator is an odd
//! derivation. Expanding every covariant derivative, curvature, commutator, and
//! gauge transformation into this word basis makes a zero residual an exact
//! coefficient-by-coefficient identity.

use std::collections::BTreeMap;

use serde::Serialize;

const N_DIRECTIONS: usize = 10;
const PLUS: usize = 0;
const MINUS: usize = 1;

const fn spatial(i: usize) -> usize {
    i + 2
}

/// The independent fields in Eqs. (22) and (23). `Chi(a)` and `G(a)` are the
/// seven coordinates T_{a8} of a Spin(7) antiselfdual two-form.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Field {
    APlus,
    AMinus,
    A(usize),
    Eta,
    Psi(usize),
    Chi(usize),
    G(usize),
}

impl Field {
    fn odd(self) -> bool {
        matches!(self, Self::Eta | Self::Psi(_) | Self::Chi(_))
    }
}

type Powers = [u8; N_DIRECTIONS];

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Jet {
    field: Field,
    powers: Powers,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, PartialOrd, Ord)]
struct Word(Vec<Jet>);

/// Canonical exact sum of noncommutative field-jet words.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Polynomial(BTreeMap<Word, i64>);

impl Polynomial {
    fn atom(field: Field) -> Self {
        Self::jet(field, [0; N_DIRECTIONS])
    }

    fn jet(field: Field, powers: Powers) -> Self {
        let mut terms = BTreeMap::new();
        terms.insert(Word(vec![Jet { field, powers }]), 1);
        Self(terms)
    }

    fn add_word(&mut self, coefficient: i64, word: Word) {
        if coefficient == 0 {
            return;
        }
        let value = self.0.entry(word.clone()).or_insert(0);
        *value += coefficient;
        if *value == 0 {
            self.0.remove(&word);
        }
    }

    fn add_scaled(&mut self, other: &Self, scale: i64) {
        for (word, coefficient) in &other.0 {
            self.add_word(scale * coefficient, word.clone());
        }
    }

    fn scaled(&self, scale: i64) -> Self {
        let mut out = Self::default();
        out.add_scaled(self, scale);
        out
    }

    fn product(&self, other: &Self) -> Self {
        let mut out = Self::default();
        for (left_word, left_coefficient) in &self.0 {
            for (right_word, right_coefficient) in &other.0 {
                let mut factors = left_word.0.clone();
                factors.extend(right_word.0.iter().cloned());
                out.add_word(left_coefficient * right_coefficient, Word(factors));
            }
        }
        out
    }

    fn derivative(&self, direction: usize) -> Self {
        assert!(direction < N_DIRECTIONS);
        let mut out = Self::default();
        // The ordinary derivative is an even derivation.
        for (word, coefficient) in &self.0 {
            for position in 0..word.0.len() {
                let mut differentiated = word.clone();
                differentiated.0[position].powers[direction] = differentiated.0[position].powers
                    [direction]
                    .checked_add(1)
                    .expect("derivative degree overflow");
                out.add_word(*coefficient, differentiated);
            }
        }
        out
    }

    fn derivative_powers(&self, powers: Powers) -> Self {
        let mut out = self.clone();
        for (direction, &degree) in powers.iter().enumerate() {
            for _ in 0..degree {
                out = out.derivative(direction);
            }
        }
        out
    }

    pub fn is_zero(&self) -> bool {
        self.0.is_empty()
    }

    pub fn term_count(&self) -> usize {
        self.0.len()
    }

    /// Stable, re-checkable rendering of the canonical residual terms.
    pub fn canonical_terms(&self) -> Vec<String> {
        self.0
            .iter()
            .map(|(word, coefficient)| {
                let factors = word
                    .0
                    .iter()
                    .map(|jet| format!("{:?}@{:?}", jet.field, jet.powers))
                    .collect::<Vec<_>>()
                    .join(" * ");
                format!("{coefficient:+} [{factors}]")
            })
            .collect()
    }
}

fn commutator(left: &Polynomial, right: &Polynomial) -> Polynomial {
    let mut out = left.product(right);
    out.add_scaled(&right.product(left), -1);
    out
}

fn potential(mu: usize) -> Field {
    match mu {
        PLUS => Field::APlus,
        MINUS => Field::AMinus,
        2..=9 => Field::A(mu - 2),
        _ => panic!("invalid spacetime direction"),
    }
}

fn covariant_derivative(mu: usize, expression: &Polynomial) -> Polynomial {
    // D_mu X = partial_mu X + [A_mu,X].
    let mut out = expression.derivative(mu);
    out.add_scaled(&commutator(&Polynomial::atom(potential(mu)), expression), 1);
    out
}

fn curvature(mu: usize, nu: usize) -> Polynomial {
    // F_mu,nu = partial_mu A_nu - partial_nu A_mu + [A_mu,A_nu].
    let mut out = Polynomial::atom(potential(nu)).derivative(mu);
    out.add_scaled(&Polynomial::atom(potential(mu)).derivative(nu), -1);
    out.add_scaled(
        &commutator(
            &Polynomial::atom(potential(mu)),
            &Polynomial::atom(potential(nu)),
        ),
        1,
    );
    out
}

fn all_fields() -> Vec<Field> {
    let mut fields = Vec::with_capacity(33);
    fields.push(Field::APlus);
    fields.push(Field::AMinus);
    fields.extend((0..8).map(Field::A));
    fields.push(Field::Eta);
    fields.extend((0..8).map(Field::Psi));
    fields.extend((0..7).map(Field::Chi));
    fields.extend((0..7).map(Field::G));
    fields
}

// ---------------------------------------------------------------------------
// Exact Spin(7) projector in the convention of BBBM Eqs. (14) and (23).
// ---------------------------------------------------------------------------

const FANO: [(usize, usize, usize); 7] = [
    (1, 2, 3),
    (1, 4, 5),
    (1, 7, 6),
    (2, 4, 6),
    (2, 5, 7),
    (3, 4, 7),
    (3, 6, 5),
];

fn permutation_sign(values: &[usize]) -> i64 {
    let inversions = (0..values.len())
        .flat_map(|i| ((i + 1)..values.len()).map(move |j| (i, j)))
        .filter(|&(i, j)| values[i] > values[j])
        .count();
    if inversions % 2 == 0 {
        1
    } else {
        -1
    }
}

fn phi(a: usize, b: usize, c: usize) -> i64 {
    if a == b || a == c || b == c || a >= 7 || b >= 7 || c >= 7 {
        return 0;
    }
    for &(x, y, z) in &FANO {
        let base = [x - 1, y - 1, z - 1];
        let mut sorted_base = base;
        let mut sorted_input = [a, b, c];
        sorted_base.sort_unstable();
        sorted_input.sort_unstable();
        if sorted_base == sorted_input {
            return permutation_sign(&base) * permutation_sign(&[a, b, c]);
        }
    }
    0
}

fn omega(i: usize, j: usize, k: usize, l: usize) -> i64 {
    if i == j || i == k || i == l || j == k || j == l || k == l {
        return 0;
    }
    let indices = [i, j, k, l];
    if let Some(position) = indices.iter().position(|&x| x == 7) {
        let abc: Vec<_> = indices.iter().copied().filter(|&x| x != 7).collect();
        let move_sign = if (3 - position) % 2 == 0 { 1 } else { -1 };
        return move_sign * phi(abc[0], abc[1], abc[2]);
    }
    let rest: Vec<_> = (0..7).filter(|x| !indices.contains(x)).collect();
    let mut seven = indices.to_vec();
    seven.extend(rest.iter().copied());
    permutation_sign(&seven) * phi(rest[0], rest[1], rest[2])
}

fn canonical_pair(i: usize, j: usize) -> Option<((usize, usize), i64)> {
    if i == j {
        None
    } else if i < j {
        Some(((i, j), 1))
    } else {
        Some(((j, i), -1))
    }
}

/// `q=8P^-` in the individual-index convention used in Eq. (23). On the 28
/// canonical antisymmetric pairs this is `I-Omega=4P`, with `q*q=4q`.
fn q(i: usize, j: usize, k: usize, l: usize) -> i64 {
    let Some(((i, j), left_sign)) = canonical_pair(i, j) else {
        return 0;
    };
    let Some(((k, l), right_sign)) = canonical_pair(k, l) else {
        return 0;
    };
    left_sign * right_sign * (i64::from(i == k && j == l) - omega(i, j, k, l))
}

fn projected_pair(i: usize, j: usize, constructor: fn(usize) -> Field) -> Polynomial {
    let mut out = Polynomial::default();
    for a in 0..7 {
        out.add_scaled(&Polynomial::atom(constructor(a)), q(i, j, a, 7));
    }
    out
}

fn chi(i: usize, j: usize) -> Polynomial {
    projected_pair(i, j, Field::Chi)
}

fn g(i: usize, j: usize) -> Polynomial {
    projected_pair(i, j, Field::G)
}

// ---------------------------------------------------------------------------
// Odd transformations from the original TeX, Eqs. (22) and (23).
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, Debug)]
enum Charge {
    Scalar,
    Vector(usize),
}

fn delta(charge: Charge, field: Field) -> Polynomial {
    match charge {
        Charge::Scalar => delta0(field),
        Charge::Vector(i) => deltai(i, field),
    }
}

fn delta0(field: Field) -> Polynomial {
    match field {
        Field::A(i) => Polynomial::atom(Field::Psi(i)),
        Field::APlus => Polynomial::default(),
        Field::AMinus => Polynomial::atom(Field::Eta),
        Field::Psi(i) => curvature(spatial(i), PLUS).scaled(-1),
        Field::Eta => curvature(PLUS, MINUS),
        Field::Chi(a) => Polynomial::atom(Field::G(a)),
        Field::G(a) => covariant_derivative(PLUS, &Polynomial::atom(Field::Chi(a))),
    }
}

fn deltai(i: usize, field: Field) -> Polynomial {
    assert!(i < 8);
    match field {
        Field::A(j) => {
            let mut out = chi(i, j).scaled(-1);
            if i == j {
                out.add_scaled(&Polynomial::atom(Field::Eta), -1);
            }
            out
        }
        Field::APlus => Polynomial::atom(Field::Psi(i)).scaled(-1),
        Field::AMinus => Polynomial::default(),
        Field::Psi(j) => {
            let mut out = curvature(spatial(i), spatial(j));
            out.add_scaled(&g(i, j), 1);
            if i == j {
                out.add_scaled(&curvature(PLUS, MINUS), 1);
            }
            out
        }
        Field::Eta => curvature(spatial(i), MINUS),
        Field::Chi(a) => {
            let mut out = Polynomial::default();
            for l in 0..8 {
                out.add_scaled(&curvature(spatial(l), MINUS), q(a, 7, i, l));
            }
            out
        }
        Field::G(a) => {
            let mut out = covariant_derivative(spatial(i), &Polynomial::atom(Field::Chi(a)));
            for l in 0..8 {
                let mut parenthesis =
                    covariant_derivative(spatial(l), &Polynomial::atom(Field::Eta));
                parenthesis.add_scaled(
                    &covariant_derivative(MINUS, &Polynomial::atom(Field::Psi(l))),
                    -1,
                );
                out.add_scaled(&parenthesis, -q(a, 7, i, l));
            }
            out
        }
    }
}

/// Apply one odd supersymmetry generator to an exact polynomial. The sign at
/// each word position is the parity of the prefix, implementing the graded
/// Leibniz rule rather than treating fermions as commuting symbols.
fn apply_delta(charge: Charge, polynomial: &Polynomial) -> Polynomial {
    let mut out = Polynomial::default();
    for (word, coefficient) in &polynomial.0 {
        let mut prefix_is_odd = false;
        for position in 0..word.0.len() {
            let jet = &word.0[position];
            let varied_jet = delta(charge, jet.field).derivative_powers(jet.powers);
            let sign = if prefix_is_odd { -1 } else { 1 };
            for (varied_word, varied_coefficient) in &varied_jet.0 {
                let mut factors = Vec::new();
                factors.extend(word.0[..position].iter().cloned());
                factors.extend(varied_word.0.iter().cloned());
                factors.extend(word.0[(position + 1)..].iter().cloned());
                out.add_word(sign * coefficient * varied_coefficient, Word(factors));
            }
            prefix_is_odd ^= jet.field.odd();
        }
    }
    out
}

fn compose(left: Charge, right: Charge, field: Field) -> Polynomial {
    apply_delta(left, &delta(right, field))
}

// With D=partial+[A,.], the convention compatible with Eq. (24) is
// gauge(lambda) A_mu=-D_mu lambda and gauge(lambda) X=[lambda,X].
fn gauge_transformation(parameter: Field, field: Field) -> Polynomial {
    let lambda = Polynomial::atom(parameter);
    match field {
        Field::APlus => covariant_derivative(PLUS, &lambda).scaled(-1),
        Field::AMinus => covariant_derivative(MINUS, &lambda).scaled(-1),
        Field::A(i) => covariant_derivative(spatial(i), &lambda).scaled(-1),
        _ => commutator(&lambda, &Polynomial::atom(field)),
    }
}

fn translation_plus_gauge(direction: usize, parameter: Field, field: Field) -> Polynomial {
    let mut out = Polynomial::atom(field).derivative(direction);
    out.add_scaled(&gauge_transformation(parameter, field), 1);
    out
}

/// A nonzero exact canonical residual from one component closure relation.
#[derive(Clone, Debug)]
pub struct Residual {
    pub relation: String,
    pub field: Field,
    pub polynomial: Polynomial,
}

/// Verify Eq. (24) on all 33 independent fields by direct expansion of
/// Eqs. (22) and (23). This evaluates 1,485 field-level identities.
pub fn component_closure_residuals() -> Vec<Residual> {
    let mut residuals = Vec::new();
    for field in all_fields() {
        let mut scalar = compose(Charge::Scalar, Charge::Scalar, field);
        scalar.add_scaled(&translation_plus_gauge(PLUS, Field::APlus, field), -1);
        if !scalar.is_zero() {
            residuals.push(Residual {
                relation: "delta_0^2".to_string(),
                field,
                polynomial: scalar,
            });
        }

        for i in 0..8 {
            let mut mixed = compose(Charge::Scalar, Charge::Vector(i), field);
            mixed.add_scaled(&compose(Charge::Vector(i), Charge::Scalar, field), 1);
            mixed.add_scaled(&translation_plus_gauge(spatial(i), Field::A(i), field), -1);
            if !mixed.is_zero() {
                residuals.push(Residual {
                    relation: format!("{{delta_0,delta_{i}}}"),
                    field,
                    polynomial: mixed,
                });
            }

            for j in i..8 {
                let mut vectors = compose(Charge::Vector(i), Charge::Vector(j), field);
                vectors.add_scaled(&compose(Charge::Vector(j), Charge::Vector(i), field), 1);
                // The braces on delta_{ {i} delta_{j} } in Eq. (24) denote
                // normalized symmetrization. Check the raw anticommutator by
                // multiplying the stated diagonal right side by two.
                if i == j {
                    vectors.add_scaled(&translation_plus_gauge(MINUS, Field::AMinus, field), -2);
                }
                if !vectors.is_zero() {
                    residuals.push(Residual {
                        relation: format!("{{delta_{i},delta_{j}}}"),
                        field,
                        polynomial: vectors,
                    });
                }
            }
        }
    }
    residuals
}

/// Machine-readable certificate for the full nonabelian component calculation.
#[derive(Debug, Serialize)]
pub struct NonabelianClosureReport {
    pub source: &'static str,
    pub algebra: &'static str,
    pub raw_bosonic_fields: usize,
    pub fermionic_fields: usize,
    pub independent_fields_checked: usize,
    pub charge_pair_relations_per_field: usize,
    pub exact_relations_checked: usize,
    pub residual_relations: usize,
    pub residual_terms: usize,
    pub used_equations_of_motion: bool,
    pub used_integration_by_parts: bool,
    pub used_trace_cyclicity: bool,
    pub all_nonabelian_relations_close_modulo_gauge: bool,
    pub boundary: &'static str,
}

pub fn run() -> NonabelianClosureReport {
    let residuals = component_closure_residuals();
    NonabelianClosureReport {
        source: "arXiv:0705.2002 original TeX, Eqs. (22)-(24)",
        algebra: "exact free associative differential superalgebra with noncommuting adjoint-valued field jets",
        raw_bosonic_fields: 17,
        fermionic_fields: 16,
        independent_fields_checked: 33,
        charge_pair_relations_per_field: 45,
        exact_relations_checked: 33 * 45,
        residual_relations: residuals.len(),
        residual_terms: residuals
            .iter()
            .map(|residual| residual.polynomial.term_count())
            .sum(),
        used_equations_of_motion: false,
        used_integration_by_parts: false,
        used_trace_cyclicity: false,
        all_nonabelian_relations_close_modulo_gauge: residuals.is_empty(),
        boundary: "verifies the nine printed charges in flat ten-dimensional super-Yang-Mills; does not reconstruct the seven discarded charges or address global gauge topology",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn odd_leibniz_rule_has_the_required_fermion_sign() {
        let eta = Polynomial::atom(Field::Eta);
        let psi = Polynomial::atom(Field::Psi(0));
        let product = eta.product(&psi);
        let actual = apply_delta(Charge::Scalar, &product);

        let mut expected = delta0(Field::Eta).product(&psi);
        expected.add_scaled(&eta.product(&delta0(Field::Psi(0))), -1);
        assert_eq!(actual, expected);
    }

    #[test]
    fn covariant_derivative_commutator_is_curvature_action() {
        for field in [Field::Eta, Field::Psi(3), Field::Chi(2), Field::G(5)] {
            let x = Polynomial::atom(field);
            let mut left = covariant_derivative(3, &covariant_derivative(7, &x));
            left.add_scaled(&covariant_derivative(7, &covariant_derivative(3, &x)), -1);
            left.add_scaled(&commutator(&curvature(3, 7), &x), -1);
            assert!(
                left.is_zero(),
                "[D_3,D_7] residual: {:?}",
                left.canonical_terms()
            );
        }
    }

    #[test]
    fn spin7_operator_is_exact_rank_seven_projector() {
        let pairs: Vec<_> = (0..8)
            .flat_map(|i| ((i + 1)..8).map(move |j| (i, j)))
            .collect();
        let matrix: Vec<Vec<i64>> = pairs
            .iter()
            .map(|&(i, j)| pairs.iter().map(|&(k, l)| q(i, j, k, l)).collect())
            .collect();
        for row in 0..28 {
            for col in 0..28 {
                let product: i64 = (0..28).map(|mid| matrix[row][mid] * matrix[mid][col]).sum();
                assert_eq!(product, 4 * matrix[row][col]);
                assert_eq!(matrix[row][col], matrix[col][row]);
            }
        }
        // trace(Q/4)=7, hence rank(P)=7 because P is idempotent.
        assert_eq!((0..28).map(|i| matrix[i][i]).sum::<i64>(), 28);
    }

    #[test]
    fn every_nonabelian_component_relation_has_zero_exact_residual() {
        let residuals = component_closure_residuals();
        assert!(
            residuals.is_empty(),
            "nonabelian BBBM closure residuals: {:#?}",
            residuals
                .iter()
                .map(|r| (&r.relation, r.field, r.polynomial.canonical_terms()))
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn report_counts_all_nonabelian_relations() {
        let report = run();
        assert_eq!(report.exact_relations_checked, 1_485);
        assert_eq!(report.residual_relations, 0);
        assert_eq!(report.residual_terms, 0);
        assert!(report.all_nonabelian_relations_close_modulo_gauge);
        assert!(!report.used_equations_of_motion);
    }
}
