//! R8-isotypic block projection of signed S8 representations.
//!
//! R8 = {e, r1, ..., r7} ≅ (Z/2)^3 acts regularly on {0,...,7} via the
//! Rana subgroup (arXiv:2304.09830 Eq. 3.23). The isotypic decomposition of
//! C^8 under this action is the Walsh-Hadamard (Fourier) transform.
//!
//! This module projects each L_I signed permutation into the R8 Fourier basis
//! using exact rational arithmetic (all entries are multiples of 1/8), then
//! classifies the 16 ordinary-closing S8 representations by their exact
//! diagonal tensors.
//!
//! SCOPE: These invariants classify recursion-basis construction families.
//! They are NOT proven physical invariants; the diagonal tensor depends on
//! the choice of R8 basis applied identically to bosons and fermions, and
//! transforms nontrivially under independent node basis changes and color
//! permutations. The mutation tests in this module document which
//! transformations preserve and which break the classification.

use crate::lr_matrix::AdinkraRep;
use crate::signed_perm::SignedPerm;
use serde::Serialize;

/// The 8 elements of R8 as 0-indexed permutations of {0,...,7}.
/// Generated by a=(01)(23)(45)(67), b=(02)(13)(46)(57), c=(04)(15)(26)(37).
/// Element ordering: e, a, b, ab, c, ac, bc, abc.
pub const R8_ELEMENTS: [[usize; 8]; 8] = [
    [0, 1, 2, 3, 4, 5, 6, 7], // e
    [1, 0, 3, 2, 5, 4, 7, 6], // a
    [2, 3, 0, 1, 6, 7, 4, 5], // b
    [3, 2, 1, 0, 7, 6, 5, 4], // ab
    [4, 5, 6, 7, 0, 1, 2, 3], // c
    [5, 4, 7, 6, 1, 0, 3, 2], // ac
    [6, 7, 4, 5, 2, 3, 0, 1], // bc
    [7, 6, 5, 4, 3, 2, 1, 0], // abc
];

/// Hadamard sign: (-1)^popcount(i & j).
fn hadamard_sign(i: usize, j: usize) -> i16 {
    if (i & j).count_ones() % 2 == 0 { 1 } else { -1 }
}

/// Walsh-Hadamard entry: U[i][j] = (1/sqrt(8)) * (-1)^popcount(i & j).
fn hadamard_entry(i: usize, j: usize) -> f64 {
    hadamard_sign(i, j) as f64 / (8.0_f64).sqrt()
}

/// The 8x8 Walsh-Hadamard matrix U (floating point, for legacy/validation).
pub fn r8_fourier_basis() -> [[f64; 8]; 8] {
    let mut u = [[0.0; 8]; 8];
    for i in 0..8 {
        for j in 0..8 {
            u[i][j] = hadamard_entry(i, j);
        }
    }
    u
}

/// Exact projection: compute 8 * (H L H^T)[a][b] as an i16.
///
/// For signed permutation L with perm pi and signs s_i:
///   8 * (H L H^T)[a][b] = sum_i  s_i * (-1)^(popcount(a&i) + popcount(pi(i)&b))
///
/// Each term is +/-1, so the sum is in [-8, 8].
pub fn project_exact(sp: &SignedPerm) -> [[i16; 8]; 8] {
    let mut result = [[0i16; 8]; 8];
    for a in 0..8 {
        for b in 0..8 {
            let mut sum = 0i16;
            for i in 0..8 {
                let s = sp.sign[i] as i16;
                let pi_i = sp.perm[i] as usize;
                let h_sign = hadamard_sign(a, i) * hadamard_sign(pi_i, b);
                sum += s * h_sign;
            }
            result[a][b] = sum;
        }
    }
    result
}

/// Per-color exact block projection.
#[derive(Debug, Clone, Serialize)]
pub struct ExactColorProjection {
    pub color: usize,
    /// 8 * (H L_I H^T), exact integers in [-8, 8].
    pub exact_matrix: [[i16; 8]; 8],
    /// Diagonal of exact_matrix.
    pub exact_diagonal: [i16; 8],
}

/// Full exact block report for one representation.
#[derive(Debug, Clone, Serialize)]
pub struct ExactBlockReport {
    pub label: String,
    pub projections: Vec<ExactColorProjection>,
    /// All 8 exact diagonals concatenated (n_colors * 8 entries).
    pub diagonal_tensor: Vec<i16>,
    /// Per-color sorted diagonal (for R8-automorphism-invariant comparison).
    pub sorted_diagonal_tensor: Vec<Vec<i16>>,
    /// Coupling fingerprint: for each irrep, bitmask of which others couple.
    pub coupling_fingerprint: [u8; 8],
}

/// R8 subgroup-restriction profile: per-color diagonal values organized
/// under the subgroup chain (Z/2)^3 > (Z/2)^2 > Z/2 > {e}.
#[derive(Debug, Clone, Serialize)]
pub struct R8SubgroupRestriction {
    pub label: String,
    /// Per-color, the 4 paired sums d[k] + d[k XOR 4] for (Z/2)^2 = <a,b>.
    pub z2_squared_sums: Vec<[i16; 4]>,
    /// Per-color, the 2 quadrupled sums for Z/2 = <a>.
    pub z2_sums: Vec<[i16; 2]>,
    /// Source pair type extracted from the label (e.g., "{CM,TM}").
    pub source_pair_type: String,
}

/// Compute the exact block report for one rep.
pub fn compute_exact_report(rep: &AdinkraRep, label: &str) -> ExactBlockReport {
    let n = rep.n;
    let mut projections = Vec::with_capacity(n);
    let mut diagonal_tensor = Vec::with_capacity(n * 8);
    let mut sorted_diagonal_tensor = Vec::with_capacity(n);
    let mut fingerprint = [0u8; 8];

    for color in 0..n {
        let exact = project_exact(&rep.l_matrices[color]);
        let diag: [i16; 8] = std::array::from_fn(|i| exact[i][i]);
        diagonal_tensor.extend_from_slice(&diag);

        let mut sorted = diag.to_vec();
        sorted.sort();
        sorted_diagonal_tensor.push(sorted);

        for i in 0..8 {
            for j in (i + 1)..8 {
                if exact[i][j] != 0 || exact[j][i] != 0 {
                    fingerprint[i] |= 1 << j;
                    fingerprint[j] |= 1 << i;
                }
            }
        }

        projections.push(ExactColorProjection {
            color,
            exact_matrix: exact,
            exact_diagonal: diag,
        });
    }

    ExactBlockReport {
        label: label.to_string(),
        projections,
        diagonal_tensor,
        sorted_diagonal_tensor,
        coupling_fingerprint: fingerprint,
    }
}

/// Compute R8 subgroup-restriction profile.
pub fn subgroup_restriction(report: &ExactBlockReport) -> R8SubgroupRestriction {
    let mut z2sq = Vec::with_capacity(report.projections.len());
    let mut z2s = Vec::with_capacity(report.projections.len());

    for proj in &report.projections {
        let d = &proj.exact_diagonal;
        z2sq.push(std::array::from_fn(|k| d[k] + d[k ^ 4]));
        z2s.push([d[0] + d[2] + d[4] + d[6], d[1] + d[3] + d[5] + d[7]]);
    }

    R8SubgroupRestriction {
        label: report.label.clone(),
        z2_squared_sums: z2sq,
        z2_sums: z2s,
        source_pair_type: extract_source_pair_type(&report.label),
    }
}

fn extract_source_pair_type(label: &str) -> String {
    let parts: Vec<&str> = label.split("->").collect();
    if parts.len() != 2 {
        return "unknown".to_string();
    }
    let first = parts[0].trim();
    let second = parts[1].split('_').next().unwrap_or("").trim();
    let mut pair = [first, second];
    pair.sort();
    format!("{{{},{}}}", pair[0], pair[1])
}

/// Classification summary across multiple reps.
#[derive(Debug, Clone, Serialize)]
pub struct ClassificationSummary {
    pub rep_count: usize,
    /// Classes by exact ordered diagonal tensor.
    pub ordered_classes: Vec<(Vec<i16>, Vec<String>)>,
    /// Classes by sorted diagonal multisets (R8-automorphism-invariant).
    pub sorted_classes: Vec<(Vec<Vec<i16>>, Vec<String>)>,
    /// Classes by coupling fingerprint.
    pub fingerprint_classes: Vec<([u8; 8], Vec<String>)>,
}

/// Classify reports by exact diagonal tensors.
pub fn classify(reports: &[ExactBlockReport]) -> ClassificationSummary {
    use std::collections::BTreeMap;

    let mut ordered: BTreeMap<Vec<i16>, Vec<String>> = BTreeMap::new();
    let mut sorted: BTreeMap<Vec<Vec<i16>>, Vec<String>> = BTreeMap::new();
    let mut fps: BTreeMap<[u8; 8], Vec<String>> = BTreeMap::new();

    for report in reports {
        ordered
            .entry(report.diagonal_tensor.clone())
            .or_default()
            .push(report.label.clone());
        sorted
            .entry(report.sorted_diagonal_tensor.clone())
            .or_default()
            .push(report.label.clone());
        fps.entry(report.coupling_fingerprint)
            .or_default()
            .push(report.label.clone());
    }

    ClassificationSummary {
        rep_count: reports.len(),
        ordered_classes: ordered.into_iter().collect(),
        sorted_classes: sorted.into_iter().collect(),
        fingerprint_classes: fps.into_iter().collect(),
    }
}

// --- Legacy floating-point API (kept for S4/V4 validation test) ---

fn mat_mul(a: &[[f64; 8]; 8], b: &[[f64; 8]; 8]) -> [[f64; 8]; 8] {
    let mut c = [[0.0; 8]; 8];
    for i in 0..8 {
        for k in 0..8 {
            if a[i][k] == 0.0 {
                continue;
            }
            for j in 0..8 {
                c[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    c
}

fn mat_transpose(a: &[[f64; 8]; 8]) -> [[f64; 8]; 8] {
    let mut t = [[0.0; 8]; 8];
    for i in 0..8 {
        for j in 0..8 {
            t[i][j] = a[j][i];
        }
    }
    t
}

fn mat_identity() -> [[f64; 8]; 8] {
    let mut m = [[0.0; 8]; 8];
    for i in 0..8 {
        m[i][i] = 1.0;
    }
    m
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hadamard_is_orthogonal() {
        let u = r8_fourier_basis();
        let ut = mat_transpose(&u);
        let product = mat_mul(&u, &ut);
        let id = mat_identity();
        for i in 0..8 {
            for j in 0..8 {
                assert!(
                    (product[i][j] - id[i][j]).abs() < 1e-12,
                    "U*U^T[{},{}] = {} (expected {})",
                    i,
                    j,
                    product[i][j],
                    id[i][j]
                );
            }
        }
    }

    #[test]
    fn hadamard_diagonalizes_r8_elements() {
        let u = r8_fourier_basis();
        let ut = mat_transpose(&u);
        for (idx, elem) in R8_ELEMENTS.iter().enumerate() {
            let mut rho = [[0.0; 8]; 8];
            for i in 0..8 {
                rho[i][elem[i]] = 1.0;
            }
            let diag = mat_mul(&u, &mat_mul(&rho, &ut));
            for i in 0..8 {
                for j in 0..8 {
                    if i != j {
                        assert!(
                            diag[i][j].abs() < 1e-12,
                            "R8 element {} not diagonalized: off-diag[{},{}] = {}",
                            idx,
                            i,
                            j,
                            diag[i][j]
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn r8_diagonal_entries_are_characters() {
        let u = r8_fourier_basis();
        let ut = mat_transpose(&u);
        for (idx, elem) in R8_ELEMENTS.iter().enumerate() {
            let mut rho = [[0.0; 8]; 8];
            for i in 0..8 {
                rho[i][elem[i]] = 1.0;
            }
            let diag = mat_mul(&u, &mat_mul(&rho, &ut));
            for j in 0..8 {
                let expected = if (idx & j).count_ones() % 2 == 0 {
                    1.0
                } else {
                    -1.0
                };
                assert!(
                    (diag[j][j] - expected).abs() < 1e-12,
                    "R8[{}] in irrep {}: got {}, expected {}",
                    idx,
                    j,
                    diag[j][j],
                    expected
                );
            }
        }
    }

    #[test]
    fn exact_projection_matches_floating_point() {
        let sp = SignedPerm::from_parts(
            vec![1, 0, 3, 2, 5, 4, 7, 6],
            vec![1, -1, 1, -1, 1, -1, 1, -1],
        )
        .unwrap();
        let exact = project_exact(&sp);
        let u = r8_fourier_basis();
        let ut = mat_transpose(&u);
        let mut dense = [[0.0; 8]; 8];
        for row in 0..8 {
            dense[row][sp.perm[row] as usize] = sp.sign[row] as f64;
        }
        let float_proj = mat_mul(&u, &mat_mul(&dense, &ut));
        for a in 0..8 {
            for b in 0..8 {
                let from_exact = exact[a][b] as f64 / 8.0;
                assert!(
                    (float_proj[a][b] - from_exact).abs() < 1e-12,
                    "exact/float mismatch at [{},{}]: exact={} float={}",
                    a,
                    b,
                    from_exact,
                    float_proj[a][b]
                );
            }
        }
    }

    #[test]
    fn exact_projection_entries_bounded() {
        use crate::permutahedron_s8_signed_recursion as sr;
        let artifact = sr::build();
        for pair in &artifact.ordered_pairs {
            for candidate in &pair.candidates {
                if candidate.closure.sparse_garden_passed && candidate.closure.residual_entries == 0
                {
                    let rep = sr::build_rep(&candidate.permutations, &candidate.boolean_factors);
                    for color in 0..rep.n {
                        let exact = project_exact(&rep.l_matrices[color]);
                        for a in 0..8 {
                            for b in 0..8 {
                                assert!(
                                    exact[a][b].abs() <= 8,
                                    "entry [{},{}] = {} exceeds bound",
                                    a,
                                    b,
                                    exact[a][b]
                                );
                            }
                        }
                    }
                }
            }
        }
    }

    #[test]
    fn project_identity_is_identity() {
        let exact = project_exact(&SignedPerm::identity(8));
        for i in 0..8 {
            for j in 0..8 {
                let expected = if i == j { 8 } else { 0 };
                assert_eq!(exact[i][j], expected, "identity[{},{}]", i, j);
            }
        }
    }

    #[test]
    fn project_r8_element_is_diagonal() {
        for elem in &R8_ELEMENTS[1..] {
            let perm: Vec<u16> = elem.iter().map(|&x| x as u16).collect();
            let sp = SignedPerm::from_parts(perm, vec![1; 8]).unwrap();
            let exact = project_exact(&sp);
            for i in 0..8 {
                for j in 0..8 {
                    if i != j {
                        assert_eq!(
                            exact[i][j], 0,
                            "R8 elem off-diag [{},{}] = {}",
                            i, j, exact[i][j]
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn s4_v4_block_analysis_validates() {
        let cs = crate::lr_matrix::AdinkraRep {
            n: 4,
            d: 4,
            l_matrices: vec![
                SignedPerm::from_parts(vec![0, 1, 2, 3], vec![1, 1, 1, 1]).unwrap(),
                SignedPerm::from_parts(vec![1, 0, 3, 2], vec![1, -1, 1, -1]).unwrap(),
                SignedPerm::from_parts(vec![2, 3, 0, 1], vec![1, -1, -1, 1]).unwrap(),
                SignedPerm::from_parts(vec![3, 2, 1, 0], vec![1, 1, -1, -1]).unwrap(),
            ],
        };
        assert!(cs.verify_garden_algebra());

        let sqrt4 = 2.0_f64;
        let u4 = |i: usize, j: usize| -> f64 {
            let sign = if (i & j).count_ones() % 2 == 0 {
                1.0
            } else {
                -1.0
            };
            sign / sqrt4
        };
        let l1 = &cs.l_matrices[1];
        let mut m = [[0.0f64; 4]; 4];
        for row in 0..4 {
            m[row][l1.perm[row] as usize] = l1.sign[row] as f64;
        }
        let mut proj = [[0.0f64; 4]; 4];
        for i in 0..4 {
            for j in 0..4 {
                for k in 0..4 {
                    for l in 0..4 {
                        proj[i][j] += u4(i, k) * m[k][l] * u4(l, j);
                    }
                }
            }
        }
        let trace: f64 = (0..4).map(|i| proj[i][i]).sum();
        assert!(
            (trace - l1.trace() as f64).abs() < 1e-10,
            "trace must be preserved: {} vs {}",
            trace,
            l1.trace()
        );
    }

    fn collect_closing_reports() -> Vec<ExactBlockReport> {
        use crate::permutahedron_s8_signed_recursion as sr;
        let artifact = sr::build();
        let mut reports = Vec::new();
        for pair in &artifact.ordered_pairs {
            for candidate in &pair.candidates {
                if candidate.closure.sparse_garden_passed && candidate.closure.residual_entries == 0
                {
                    let rep = sr::build_rep(&candidate.permutations, &candidate.boolean_factors);
                    let label = format!(
                        "{}->{}_s{}",
                        pair.first_label, pair.second_label, candidate.start_position_one_based
                    );
                    reports.push(compute_exact_report(&rep, &label));
                }
            }
        }
        reports
    }

    #[test]
    fn exact_classification_counts() {
        let reports = collect_closing_reports();
        assert_eq!(reports.len(), 16, "expected 16 closing candidates");

        let summary = classify(&reports);

        assert_eq!(
            summary.ordered_classes.len(),
            8,
            "expected exactly 8 ordered diagonal-tensor classes"
        );
        for (_, labels) in &summary.ordered_classes {
            assert_eq!(
                labels.len(),
                2,
                "each ordered class must contain exactly 2 reps, got {:?}",
                labels
            );
        }

        assert_eq!(
            summary.sorted_classes.len(),
            4,
            "expected exactly 4 sorted (automorphism-invariant) classes"
        );
        for (_, labels) in &summary.sorted_classes {
            assert_eq!(
                labels.len(),
                4,
                "each sorted class must contain exactly 4 reps, got {:?}",
                labels
            );
        }

        assert_eq!(
            summary.fingerprint_classes.len(),
            1,
            "expected exactly 1 coupling fingerprint class"
        );
    }

    #[test]
    fn sorted_classes_pure_within_source_pair() {
        let reports = collect_closing_reports();
        let summary = classify(&reports);

        for (_, labels) in &summary.sorted_classes {
            let types: std::collections::BTreeSet<_> =
                labels.iter().map(|l| extract_source_pair_type(l)).collect();
            assert_eq!(
                types.len(),
                1,
                "sorted class mixes source pair types: {:?} from {:?}",
                types,
                labels
            );
        }

        let class_types: std::collections::BTreeSet<_> = summary
            .sorted_classes
            .iter()
            .map(|(_, labels)| extract_source_pair_type(&labels[0]))
            .collect();
        assert_eq!(
            class_types,
            ["{CM,TM}", "{CM,VM}", "{VM1,VM2}", "{VM1,VM3}"]
                .into_iter()
                .map(String::from)
                .collect(),
            "sorted classes must cover exactly the 4 source pair types"
        );
    }

    #[test]
    fn ordered_classes_pair_source_target_swap() {
        let reports = collect_closing_reports();
        let summary = classify(&reports);

        for (_, labels) in &summary.ordered_classes {
            assert_eq!(labels.len(), 2);
            let t0 = extract_source_pair_type(&labels[0]);
            let t1 = extract_source_pair_type(&labels[1]);
            assert_eq!(
                t0, t1,
                "ordered class mixes source pair types: {:?}",
                labels
            );

            let parts0: Vec<&str> = labels[0].split("->").collect();
            let parts1: Vec<&str> = labels[1].split("->").collect();
            let first0 = parts0[0];
            let first1 = parts1[0];
            assert_ne!(
                first0, first1,
                "ordered class should pair source/target swaps: {:?}",
                labels
            );
        }
    }

    #[test]
    fn fixture_match_status() {
        use crate::permutahedron_s8_signed_recursion as sr;
        let artifact = sr::build();
        let mut ct_matches = 0;
        let mut total_matches = 0;
        for pair in &artifact.ordered_pairs {
            for candidate in &pair.candidates {
                if candidate.closure.sparse_garden_passed && candidate.closure.residual_entries == 0
                {
                    if let Some(label) = candidate.exact_published_system_match {
                        total_matches += 1;
                        if label == "CT" {
                            ct_matches += 1;
                        }
                    }
                }
            }
        }
        assert_eq!(
            ct_matches, 1,
            "exactly one closing rep matches the CT fixture"
        );
        assert_eq!(total_matches, 1, "only CT matches any published fixture");
    }

    #[test]
    fn mutation_boson_node_permutation_breaks_diagonal() {
        let reports = collect_closing_reports();
        let original = &reports[0];

        use crate::permutahedron_s8_signed_recursion as sr;
        let artifact = sr::build();
        let pair = &artifact.ordered_pairs[0];
        let candidate = pair
            .candidates
            .iter()
            .find(|c| c.closure.sparse_garden_passed && c.closure.residual_entries == 0)
            .unwrap();
        let rep = sr::build_rep(&candidate.permutations, &candidate.boolean_factors);

        // Apply a boson-side permutation: swap nodes 0 and 1.
        // L_I[a][b] -> L_I[sigma(a)][b] for boson perm sigma.
        let sigma = [1u16, 0, 2, 3, 4, 5, 6, 7];
        let mutated_l: Vec<SignedPerm> = rep
            .l_matrices
            .iter()
            .map(|l| {
                let new_perm: Vec<u16> = (0..8).map(|row| l.perm[sigma[row] as usize]).collect();
                let new_sign: Vec<i8> = (0..8).map(|row| l.sign[sigma[row] as usize]).collect();
                SignedPerm::from_parts(new_perm, new_sign).unwrap()
            })
            .collect();
        let mutated_rep = AdinkraRep {
            n: rep.n,
            d: rep.d,
            l_matrices: mutated_l,
        };
        let mutated_report = compute_exact_report(&mutated_rep, "mutated");

        let diag_changed = original.diagonal_tensor != mutated_report.diagonal_tensor;
        eprintln!(
            "boson node swap (0,1): diagonal tensor changed = {}",
            diag_changed
        );
        assert!(
            diag_changed,
            "boson node permutation should change the diagonal tensor (it is basis-dependent)"
        );
    }

    #[test]
    fn mutation_r8_automorphism_permutes_irrep_labels() {
        let reports = collect_closing_reports();
        let original = &reports[0];

        // GL(3,F_2) automorphism: swap generators a and b.
        // This permutes the irrep labels: bit pattern (b0,b1,b2) -> (b1,b0,b2).
        // Irrep index i = b0 + 2*b1 + 4*b2 maps to i' = b1 + 2*b0 + 4*b2.
        let auto_perm = |i: usize| -> usize {
            let b0 = i & 1;
            let b1 = (i >> 1) & 1;
            let b2 = (i >> 2) & 1;
            b1 + 2 * b0 + 4 * b2
        };

        let permuted_diag: Vec<i16> = original
            .projections
            .iter()
            .flat_map(|proj| {
                let d = &proj.exact_diagonal;
                (0..8).map(|i| d[auto_perm(i)]).collect::<Vec<_>>()
            })
            .collect();

        let mut original_sorted: Vec<Vec<i16>> = original.sorted_diagonal_tensor.clone();
        let mut permuted_per_color: Vec<Vec<i16>> = original
            .projections
            .iter()
            .map(|proj| {
                let d = &proj.exact_diagonal;
                let mut v: Vec<i16> = (0..8).map(|i| d[auto_perm(i)]).collect();
                v.sort();
                v
            })
            .collect();

        let ordered_changed = permuted_diag != original.diagonal_tensor;
        let sorted_preserved = permuted_per_color == original_sorted;

        eprintln!(
            "R8 automorphism (swap a,b): ordered diag changed = {}, sorted diag preserved = {}",
            ordered_changed, sorted_preserved
        );
        assert!(
            ordered_changed,
            "R8 automorphism should change ordered diagonal (unless symmetric)"
        );
        assert!(
            sorted_preserved,
            "R8 automorphism must preserve sorted diagonal (by construction)"
        );
    }

    #[test]
    fn subgroup_restriction_profile() {
        let reports = collect_closing_reports();
        let summary = classify(&reports);

        eprintln!("\n=== R8 SUBGROUP-RESTRICTION PROFILE ===");
        let mut seen = std::collections::BTreeSet::new();
        for report in &reports {
            let pair_type = extract_source_pair_type(&report.label);
            if !seen.insert(pair_type.clone()) {
                continue;
            }
            let sr = subgroup_restriction(report);
            eprintln!("  {} (source pair: {})", sr.label, sr.source_pair_type);
            for (color, proj) in report.projections.iter().enumerate().take(4) {
                eprintln!(
                    "    color {}: diag/8={:?}  (Z/2)^2 sums/8={:?}  Z/2 sums/8={:?}",
                    color, proj.exact_diagonal, sr.z2_squared_sums[color], sr.z2_sums[color],
                );
            }
        }

        assert_eq!(summary.sorted_classes.len(), 4);
    }

    #[test]
    fn classification_summary_output() {
        let reports = collect_closing_reports();
        let summary = classify(&reports);

        eprintln!("\n=== EXACT CLASSIFICATION SUMMARY ===");
        eprintln!(
            "16 reps -> {} ordered classes, {} sorted classes, {} fingerprint classes",
            summary.ordered_classes.len(),
            summary.sorted_classes.len(),
            summary.fingerprint_classes.len(),
        );

        eprintln!("\nOrdered classes (8 x 2 reps):");
        for (idx, (tensor, labels)) in summary.ordered_classes.iter().enumerate() {
            let diag0: Vec<i16> = tensor[..8].to_vec();
            eprintln!(
                "  class {}: {:?} (color0 diag/8 = {:?})",
                idx, labels, diag0
            );
        }

        eprintln!("\nSorted classes (4 x 4 reps):");
        for (idx, (_, labels)) in summary.sorted_classes.iter().enumerate() {
            let pair_type = extract_source_pair_type(&labels[0]);
            eprintln!("  class {}: source pair {} = {:?}", idx, pair_type, labels);
        }
    }
}
