//! Loader and verifier for the published 10D supergravity L/R matrix dataset.
//!
//! Source: arXiv:2512.12157 "10D Supergravity Numerical Data Sets for L & R
//! Matrices" and its data repository (GitHub `mcmulaz/Super-Sym`, the "Garden
//! Algebra" Mathematica file). The original repository stores *generative*
//! Mathematica code (sigma-matrix Kronecker products), not literal matrices;
//! `data/tendim_10d_lr.json` is generated by the Rust implementation in
//! `tendim_generate.rs`. The older NumPy and SymPy ports are cross-checks only.
//!
//! PROVENANCE BOUNDARY: this dataset exactly reproduces the authors' generative
//! `Garden Algebra` source at a pinned commit under its recorded basis and field
//! ordering. The source contains formulas, not a literal matrix dump, so there
//! are no upstream matrix bytes to compare. The paper's displayed examples in
//! Eqs. (6.0.5)-(6.0.6) are inconsistent with the generator and cannot be
//! reconciled by one fixed shared permutation of the displayed spinor labels.
//! Author confirmation is still needed to determine the intended L rows and
//! assembled R coefficients. See PROVENANCE.md.
//!
//! Shapes: 16 generators. L_I is nb x nf (82 x 176), R_I is nf x nb (176 x 82).
//! nb = 82 bosons, nf = 176 fermions. This is a non-valise, non-square
//! representation.
//!
//! The matrices satisfy:
//!   - Bosonic (closes):     L_I R_J + L_J R_I = 2 delta_IJ I_82
//!   - Fermionic (on-shell): R_I L_J + R_J L_I = 2 delta_IJ I_176 + 2 E_IJ
//! where E_IJ is the on-shell remnant / non-closure tensor (nonzero, including
//! on the diagonal, because the algebra closes only up to equations of motion).
//!
//! This module is intentionally self-contained: matrix multiply is hand-rolled
//! (no external linear-algebra crate) and SHA-256 is vendored below (no new
//! dependency added). It is registered in main.rs.

// Self-contained 10D-dataset validation/verifier module: every entry point is
// exercised only by this module's own #[cfg(test)] suite (and verify_lift), so the
// non-test binary sees it as dead. Kept as the lift-verifier research surface.
#![allow(dead_code)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::time::Instant;

/// Raw parsed dataset. `L[i]` is a 82x176 matrix (Vec of 82 rows, each 176
/// long). `R[i]` is a 176x82 matrix. Entries are stored as f64 (the real parts;
/// the published matrices are real even though intermediate sigma matrices are
/// complex).
#[derive(Debug, Clone, Deserialize)]
pub struct TenDimData {
    pub nb: usize,
    pub nf: usize,
    pub n: usize,
    #[serde(default)]
    pub source: String,
    #[serde(rename = "L")]
    pub l: Vec<Vec<Vec<f64>>>,
    #[serde(rename = "R")]
    pub r: Vec<Vec<Vec<f64>>>,
}

const UPSTREAM_COMMIT: &str = "8c8df92dac17853d7f6cb5b136ef2aec0efdea70";
const UPSTREAM_SOURCE_SHA256: &str =
    "d4499ad3077964b49659103fd3cc69e476ac8abe66a033f2284867a8e03b916c";
const PINNED_TOKEN_HASH: &str = "4070fbeda9028cfd6c29097dfaf20df06300026e0c44d96e40c3d4b9a8faf244";
const PINNED_RAW_JSON_SHA256: &str =
    "148e2891fe3c8cd7634e5a9232a800a88e957677b6b3a0490ddcc61063c9825f";

/// One nonzero term in a displayed transformation rule. The common `i` and
/// time derivative on the R side are factored out, following Eqs. (6.0.7) and
/// (6.0.8) of arXiv:2512.12157.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize)]
pub struct AuditTerm {
    pub field: String,
    pub coefficient: String,
}

/// Direct comparison of a worked example printed in Eqs. (6.0.5)-(6.0.6) with
/// the corresponding row of the pinned Garden Algebra regeneration.
#[derive(Debug, Clone, Serialize)]
pub struct WorkedExampleAudit {
    pub equation: &'static str,
    pub left_hand_side: String,
    pub paper_terms: Vec<AuditTerm>,
    pub regenerated_terms: Vec<AuditTerm>,
    pub direct_match: bool,
    pub direct_terms: usize,
    pub support_match: bool,
    pub classification: ComparisonClass,
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ComparisonClass {
    DirectMatch,
    SameSupportDifferentCoefficients,
    DifferentSupport,
}

#[derive(Debug, Clone, Serialize)]
pub struct MatrixContentAudit {
    pub l_entries: usize,
    pub r_entries: usize,
    pub combined_entries: usize,
    pub l_nonzero_entries: usize,
    pub r_nonzero_entries: usize,
    pub l_nonzero_per_color: Vec<usize>,
    pub r_nonzero_per_color: Vec<usize>,
}

#[derive(Debug, Clone, Serialize)]
pub struct DimensionsAudit {
    pub colors: usize,
    pub bosons: usize,
    pub fermions: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct AlgebraAudit {
    pub unordered_color_pairs_checked: usize,
    pub bosonic_relations_checked: usize,
    pub bosonic_scalar_equalities_checked: usize,
    pub bosonic_max_frobenius_residual: f64,
    pub fermionic_nonclosure_pairs: usize,
    pub fermionic_entries_examined_across_pairs: usize,
    pub fermionic_nonclosure_nonzero_entries_across_pairs: usize,
    pub nonzero_threshold: f64,
    pub fermionic_nonclosure_max_frobenius_norm: f64,
    pub fermionic_nonclosure_max_abs_entry: f64,
}

#[derive(Debug, Clone, Serialize)]
pub struct TimingAudit {
    pub load_ms: u128,
    pub content_validation_ms: u128,
    pub algebra_ms: u128,
    pub total_ms: u128,
}

#[derive(Debug, Clone, Serialize)]
pub struct BenchmarkAudit {
    pub warmup_runs: usize,
    pub measured_runs: usize,
    pub median_microseconds: u128,
    pub p95_microseconds: u128,
    pub build_profile: &'static str,
}

/// Machine-readable status report for the arXiv:2512.12157 reproduction.
#[derive(Debug, Clone, Serialize)]
pub struct ReproductionAudit {
    pub schema_version: &'static str,
    pub input_path: String,
    pub paper_revision: &'static str,
    pub paper_pdf_sha256: &'static str,
    pub declared_upstream_repository: &'static str,
    pub declared_upstream_commit: &'static str,
    pub declared_upstream_source_sha256: &'static str,
    pub raw_json_sha256: String,
    pub raw_json_sha256_matches: bool,
    pub canonical_matrix_token_hash: String,
    pub canonical_matrix_token_hash_matches: bool,
    pub canonical_token_tolerance: f64,
    pub rust_generator_entrywise_max_difference: f64,
    pub rust_generator_exact_bosonic_pairs: usize,
    pub rust_generator_matches: bool,
    pub dimensions: DimensionsAudit,
    pub matrix_content: MatrixContentAudit,
    pub boson_order: Vec<String>,
    pub fermion_order: Vec<String>,
    pub worked_examples: Vec<WorkedExampleAudit>,
    pub worked_examples_matching: usize,
    pub worked_examples_checked: usize,
    pub worked_example_terms_matching: usize,
    pub worked_example_terms_checked: usize,
    pub fixed_shared_spinor_label_permutation_reconciles_examples: bool,
    pub algebra: AlgebraAudit,
    pub run_timings: TimingAudit,
    pub algebra_benchmark: BenchmarkAudit,
    pub source_fidelity_basis: &'static str,
    pub passed: bool,
    pub conclusion: String,
}

/// Load the dataset from a JSON file produced from the Super-Sym Garden Algebra
/// code. Panics with a descriptive message on IO / parse / shape errors.
pub fn load(path: &str) -> TenDimData {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read 10D dataset {path}: {e}"));
    let data: TenDimData = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("failed to parse 10D dataset {path}: {e}"));
    data.validate_shapes();
    data
}

impl TenDimData {
    /// Sanity-check declared dimensions against the actual parsed matrices.
    pub fn validate_shapes(&self) {
        assert_eq!(self.l.len(), self.n, "expected {} L matrices", self.n);
        assert_eq!(self.r.len(), self.n, "expected {} R matrices", self.n);
        for (i, li) in self.l.iter().enumerate() {
            assert_eq!(li.len(), self.nb, "L[{i}] should have {} rows", self.nb);
            for (row_idx, row) in li.iter().enumerate() {
                assert_eq!(
                    row.len(),
                    self.nf,
                    "L[{i}] row {row_idx} should have {} cols",
                    self.nf
                );
            }
        }
        for (i, ri) in self.r.iter().enumerate() {
            assert_eq!(ri.len(), self.nf, "R[{i}] should have {} rows", self.nf);
            for (row_idx, row) in ri.iter().enumerate() {
                assert_eq!(
                    row.len(),
                    self.nb,
                    "R[{i}] row {row_idx} should have {} cols",
                    self.nb
                );
            }
        }
    }

    /// Verify both Garden relations directly from the parsed matrices.
    ///
    /// Returns `(bosonic_residual, fermionic_e_norm)` where:
    /// - `bosonic_residual` is the maximum, over all ordered pairs (I, J), of
    ///   the Frobenius norm of `L_I R_J + L_J R_I - 2 delta_IJ I_82`. For a
    ///   valid dataset this is ~0.
    /// - `fermionic_e_norm` is the maximum, over all pairs (I, J), of the
    ///   Frobenius norm of the remnant `E_IJ = (R_I L_J + R_J L_I)/2 - delta_IJ
    ///   I_176`. This is generically nonzero (the 10D on-shell remnant).
    pub fn verify_garden(&self) -> (f64, f64) {
        let mut bosonic_residual = 0.0_f64;
        let mut fermionic_e_norm = 0.0_f64;

        for i in 0..self.n {
            for j in 0..self.n {
                // Bosonic: L_I R_J + L_J R_I vs 2 delta_IJ I_82  (82x82)
                let lirj = matmul(&self.l[i], &self.r[j]); // 82x82
                let ljri = matmul(&self.l[j], &self.r[i]); // 82x82
                let delta = if i == j { 2.0 } else { 0.0 };
                let res = frob_diff_minus_scaled_identity(&lirj, &ljri, delta, self.nb);
                if res > bosonic_residual {
                    bosonic_residual = res;
                }

                // Fermionic remnant: E_IJ = (R_I L_J + R_J L_I)/2 - delta_IJ I
                let rilj = matmul(&self.r[i], &self.l[j]); // 176x176
                let rjli = matmul(&self.r[j], &self.l[i]); // 176x176
                let e_norm = e_remnant_norm(&rilj, &rjli, i == j, self.nf);
                if e_norm > fermionic_e_norm {
                    fermionic_e_norm = e_norm;
                }
            }
        }

        (bosonic_residual, fermionic_e_norm)
    }

    /// Frobenius norm of the remnant E_IJ for a single ordered pair (I, J).
    pub fn e_remnant(&self, i: usize, j: usize) -> f64 {
        let rilj = matmul(&self.r[i], &self.l[j]);
        let rjli = matmul(&self.r[j], &self.l[i]);
        e_remnant_norm(&rilj, &rjli, i == j, self.nf)
    }

    /// STRICT allowed-value-set validator.
    ///
    /// Maps every L entry to one of the exact L tokens and every R entry to one
    /// of the exact R tokens, within `VALUE_TOL` (1e-9). The allowed token sets
    /// are the Codex-confirmed value facts for this dataset:
    ///   - L in { -2, -1, 0, 1, 2, sqrt8 (= 2*sqrt2) }
    ///   - R in { 0, +-1/16, +-1/8, +-7/16, +-1/2, +-1/sqrt8 }
    ///
    /// Returns `Ok(())` if every entry matches a token, otherwise `Err` listing
    /// the first offending entries (matrix index + position + raw value).
    pub fn validate_value_sets(&self) -> Result<(), String> {
        let mut errors: Vec<String> = Vec::new();
        const MAX_REPORTED: usize = 32;

        for (mi, m) in self.l.iter().enumerate() {
            for (ri, row) in m.iter().enumerate() {
                for (ci, &v) in row.iter().enumerate() {
                    if l_token(v).is_none() {
                        if errors.len() < MAX_REPORTED {
                            errors.push(format!(
                                "L[{mi}][{ri}][{ci}] = {v:?} not an allowed L token"
                            ));
                        }
                    }
                }
            }
        }
        for (mi, m) in self.r.iter().enumerate() {
            for (ri, row) in m.iter().enumerate() {
                for (ci, &v) in row.iter().enumerate() {
                    if r_token(v).is_none() {
                        if errors.len() < MAX_REPORTED {
                            errors.push(format!(
                                "R[{mi}][{ri}][{ci}] = {v:?} not an allowed R token"
                            ));
                        }
                    }
                }
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(format!(
                "value-set validation failed ({} offending entr{}, showing up to {}):\n{}",
                errors.len(),
                if errors.len() == 1 { "y" } else { "ies" },
                MAX_REPORTED,
                errors.join("\n")
            ))
        }
    }

    /// CANONICAL SYMBOLIC TOKEN HASH.
    ///
    /// Maps each matrix entry to its exact symbolic token string (e.g. "-2",
    /// "0", "sqrt8", "-7/16", "1/sqrt8"), then serializes L followed by R as a
    /// single canonical token stream in fixed order (matrix index, row, col;
    /// tokens separated by ',', matrices/rows by structural markers) and hashes
    /// it with a vendored SHA-256.
    ///
    /// This hash depends ONLY on matrix CONTENT (the symbolic value of every
    /// entry, in order). It is invariant to:
    ///   - JSON metadata changes (source/relations/nb/nf/n field text),
    ///   - float formatting (0.5 vs 5e-1 vs 0.50000000001 within tol),
    /// because entries are first snapped to exact tokens.
    ///
    /// Panics if any entry is not an allowed token (call `validate_value_sets`
    /// first to get a descriptive error instead).
    pub fn canonical_token_hash(&self) -> String {
        let mut stream = String::with_capacity(self.n * self.nb * self.nf * 2);
        // Fixed structural framing so different shapes can never collide.
        stream.push_str("TENDIM-TOKENS-v1;");
        stream.push('L');
        for m in &self.l {
            stream.push('|');
            for row in m {
                for &v in row {
                    let t = l_token(v).unwrap_or_else(|| {
                        panic!("canonical_token_hash: L entry {v:?} is not an allowed token")
                    });
                    stream.push_str(t);
                    stream.push(',');
                }
                stream.push(';');
            }
        }
        stream.push_str("#R");
        for m in &self.r {
            stream.push('|');
            for row in m {
                for &v in row {
                    let t = r_token(v).unwrap_or_else(|| {
                        panic!("canonical_token_hash: R entry {v:?} is not an allowed token")
                    });
                    stream.push_str(t);
                    stream.push(',');
                }
                stream.push(';');
            }
        }
        sha256_hex(stream.as_bytes())
    }

    /// Evaluate every unordered color pair. The bosonic count is the number of
    /// matrix relations checked, not the number of scalar entries.
    pub fn full_algebra_audit(&self) -> AlgebraAudit {
        let mut bosonic_max = 0.0_f64;
        let mut fermionic_max = 0.0_f64;
        let mut fermionic_max_abs = 0.0_f64;
        let mut fermionic_nonzero_pairs = 0usize;
        let mut fermionic_nonzero_entries = 0usize;
        let mut pairs = 0usize;

        for i in 0..self.n {
            for j in i..self.n {
                pairs += 1;
                let lirj = matmul(&self.l[i], &self.r[j]);
                let ljri = matmul(&self.l[j], &self.r[i]);
                let delta = if i == j { 2.0 } else { 0.0 };
                bosonic_max = bosonic_max.max(frob_diff_minus_scaled_identity(
                    &lirj, &ljri, delta, self.nb,
                ));

                let rilj = matmul(&self.r[i], &self.l[j]);
                let rjli = matmul(&self.r[j], &self.l[i]);
                let mut norm_sq = 0.0_f64;
                let mut pair_nonzero = false;
                for row in 0..self.nf {
                    for col in 0..self.nf {
                        let mut e = 0.5 * (rilj[row][col] + rjli[row][col]);
                        if i == j && row == col {
                            e -= 1.0;
                        }
                        norm_sq += e * e;
                        fermionic_max_abs = fermionic_max_abs.max(e.abs());
                        if e.abs() > VALUE_TOL {
                            pair_nonzero = true;
                            fermionic_nonzero_entries += 1;
                        }
                    }
                }
                if pair_nonzero {
                    fermionic_nonzero_pairs += 1;
                }
                fermionic_max = fermionic_max.max(norm_sq.sqrt());
            }
        }

        AlgebraAudit {
            unordered_color_pairs_checked: pairs,
            bosonic_relations_checked: pairs,
            bosonic_scalar_equalities_checked: pairs * self.nb * self.nb,
            bosonic_max_frobenius_residual: bosonic_max,
            fermionic_nonclosure_pairs: fermionic_nonzero_pairs,
            fermionic_entries_examined_across_pairs: pairs * self.nf * self.nf,
            fermionic_nonclosure_nonzero_entries_across_pairs: fermionic_nonzero_entries,
            nonzero_threshold: VALUE_TOL,
            fermionic_nonclosure_max_frobenius_norm: fermionic_max,
            fermionic_nonclosure_max_abs_entry: fermionic_max_abs,
        }
    }
}

fn matrix_content_audit(data: &TenDimData) -> MatrixContentAudit {
    let count = |matrix: &[Vec<f64>]| {
        matrix
            .iter()
            .flatten()
            .filter(|&&x| x.abs() > VALUE_TOL)
            .count()
    };
    let l_nonzero_per_color = data
        .l
        .iter()
        .map(|matrix| count(matrix))
        .collect::<Vec<_>>();
    let r_nonzero_per_color = data
        .r
        .iter()
        .map(|matrix| count(matrix))
        .collect::<Vec<_>>();
    let l_entries = data.n * data.nb * data.nf;
    let r_entries = data.n * data.nf * data.nb;
    MatrixContentAudit {
        l_entries,
        r_entries,
        combined_entries: l_entries + r_entries,
        l_nonzero_entries: l_nonzero_per_color.iter().sum(),
        r_nonzero_entries: r_nonzero_per_color.iter().sum(),
        l_nonzero_per_color,
        r_nonzero_per_color,
    }
}

fn boson_order() -> Vec<String> {
    let mut out = Vec::with_capacity(82);
    for mu in 1..=9 {
        for nu in mu..=9 {
            out.push(format!("h{mu}{nu}"));
        }
    }
    for mu in 1..=9 {
        for nu in (mu + 1)..=9 {
            out.push(format!("B{mu}{nu}"));
        }
    }
    out.push("phi".to_string());
    out
}

fn fermion_order() -> Vec<String> {
    let mut out = Vec::with_capacity(176);
    for mu in 0..=9 {
        for spinor in 1..=16 {
            out.push(format!("psi{mu}({spinor})"));
        }
    }
    for spinor in 1..=16 {
        out.push(format!("chi{spinor}"));
    }
    out
}

fn terms(entries: &[f64], fields: &[String], side: char) -> Vec<AuditTerm> {
    let mut out = Vec::new();
    for (&value, field) in entries.iter().zip(fields) {
        let token = match side {
            'L' => l_token(value),
            'R' => r_token(value),
            _ => unreachable!(),
        };
        if let Some(coefficient) = token {
            if coefficient != "0" {
                out.push(AuditTerm {
                    field: field.clone(),
                    coefficient: coefficient.to_string(),
                });
            }
        } else {
            panic!("worked-example audit encountered illegal {side} value {value}");
        }
    }
    out
}

fn paper_terms(items: &[(&str, &str)]) -> Vec<AuditTerm> {
    items
        .iter()
        .map(|(field, coefficient)| AuditTerm {
            field: (*field).to_string(),
            coefficient: (*coefficient).to_string(),
        })
        .collect()
}

fn same_terms(left: &[AuditTerm], right: &[AuditTerm]) -> bool {
    let mut left = left.to_vec();
    let mut right = right.to_vec();
    left.sort();
    right.sort();
    left == right
}

fn same_support(left: &[AuditTerm], right: &[AuditTerm]) -> bool {
    left.iter()
        .map(|x| &x.field)
        .collect::<std::collections::BTreeSet<_>>()
        == right
            .iter()
            .map(|x| &x.field)
            .collect::<std::collections::BTreeSet<_>>()
}

fn classify(left: &[AuditTerm], right: &[AuditTerm]) -> ComparisonClass {
    if same_terms(left, right) {
        ComparisonClass::DirectMatch
    } else if same_support(left, right) {
        ComparisonClass::SameSupportDifferentCoefficients
    } else {
        ComparisonClass::DifferentSupport
    }
}

fn matching_term_count(left: &[AuditTerm], right: &[AuditTerm]) -> usize {
    let counts = |xs: &[AuditTerm]| {
        let mut out = BTreeMap::<(String, String), usize>::new();
        for x in xs {
            *out.entry((x.field.clone(), x.coefficient.clone()))
                .or_default() += 1;
        }
        out
    };
    let left = counts(left);
    let right = counts(right);
    left.iter()
        .map(|(term, n)| (*n).min(*right.get(term).unwrap_or(&0)))
        .sum()
}

fn worked_example_audit(data: &TenDimData) -> Vec<WorkedExampleAudit> {
    let bosons = boson_order();
    let fermions = fermion_order();
    let bidx = |name: &str| bosons.iter().position(|x| x == name).unwrap();
    let fidx = |name: &str| fermions.iter().position(|x| x == name).unwrap();

    let l_fixtures: [(&str, &[(&str, &str)]); 7] = [
        ("h11", &[("psi1(6)", "2")]),
        ("h47", &[("psi4(4)", "-1"), ("psi7(5)", "-1")]),
        ("h99", &[("psi9(11)", "2")]),
        ("B12", &[("psi1(8)", "-1"), ("psi2(6)", "1"), ("chi9", "1")]),
        (
            "B37",
            &[("psi3(4)", "1"), ("psi7(7)", "-1"), ("chi16", "1")],
        ),
        ("B89", &[("psi8(11)", "1"), ("psi9(3)", "1"), ("chi3", "1")]),
        ("phi", &[("chi1", "sqrt8")]),
    ];
    let r_fixtures: [(&str, &[(&str, &str)]); 6] = [
        ("psi1(1)", &[("h19", "1/2"), ("B19", "1/16")]),
        (
            "psi4(16)",
            &[
                ("h14", "1/2"),
                ("B14", "-1/16"),
                ("B23", "3/16"),
                ("B56", "3/16"),
                ("B78", "3/16"),
            ],
        ),
        ("psi9(16)", &[("h19", "1/2"), ("B19", "-1/16")]),
        ("chi1", &[("phi", "1/sqrt8")]),
        ("chi9", &[("B89", "-1/8")]),
        ("chi16", &[("B19", "-1/8")]),
    ];

    let mut out = Vec::with_capacity(13);
    for (lhs, expected) in l_fixtures {
        let paper = paper_terms(expected);
        let regenerated = terms(&data.l[0][bidx(lhs)], &fermions, 'L');
        let direct_match = same_terms(&paper, &regenerated);
        let direct_terms = matching_term_count(&paper, &regenerated);
        let support_match = same_support(&paper, &regenerated);
        let classification = classify(&paper, &regenerated);
        out.push(WorkedExampleAudit {
            equation: "6.0.5",
            left_hand_side: format!("Q1 {lhs}"),
            direct_match,
            direct_terms,
            support_match,
            classification,
            paper_terms: paper,
            regenerated_terms: regenerated,
        });
    }
    for (lhs, expected) in r_fixtures {
        let paper = paper_terms(expected);
        let regenerated = terms(&data.r[0][fidx(lhs)], &bosons, 'R');
        let direct_match = same_terms(&paper, &regenerated);
        let direct_terms = matching_term_count(&paper, &regenerated);
        let support_match = same_support(&paper, &regenerated);
        let classification = classify(&paper, &regenerated);
        out.push(WorkedExampleAudit {
            equation: "6.0.6",
            left_hand_side: format!("Q1 {lhs}"),
            direct_match,
            direct_terms,
            support_match,
            classification,
            paper_terms: paper,
            regenerated_terms: regenerated,
        });
    }
    out
}

/// Load the committed dataset, verify its raw bytes and tolerance-snapped token
/// identity, compare every
/// worked example displayed in Eqs. (6.0.5)-(6.0.6), and evaluate every
/// unordered bosonic and fermionic color pair.
pub fn reproduction_audit(path: &str) -> ReproductionAudit {
    reproduction_audit_with_benchmark(path, 3, 30)
}

fn reproduction_audit_with_benchmark(
    path: &str,
    warmup_runs: usize,
    measured_runs: usize,
) -> ReproductionAudit {
    let total_start = Instant::now();
    let start = Instant::now();
    let raw =
        std::fs::read(path).unwrap_or_else(|e| panic!("failed to read 10D dataset {path}: {e}"));
    let raw_hash = sha256_hex(&raw);
    let data = load(path);
    let load_ms = start.elapsed().as_millis();

    let start = Instant::now();
    data.validate_value_sets()
        .expect("10D dataset contains a value outside the pinned token sets");
    let token_hash = data.canonical_token_hash();
    let content_validation_ms = start.elapsed().as_millis();

    let examples = worked_example_audit(&data);
    let example_matches = examples.iter().filter(|x| x.direct_match).count();
    let term_matches = examples
        .iter()
        .map(|x| matching_term_count(&x.paper_terms, &x.regenerated_terms))
        .sum();
    let terms_checked = examples.iter().map(|x| x.paper_terms.len()).sum();

    let rust_generated = crate::tendim_generate::generate();
    let rust_generator_entrywise_max_difference =
        crate::tendim_generate::max_entrywise_difference(&rust_generated, &data);
    let rust_generator_exact_bosonic_pairs =
        crate::tendim_generate::verify_exact_bosonic(&rust_generated);
    let rust_generator_matches = rust_generator_entrywise_max_difference == 0.0
        && rust_generator_exact_bosonic_pairs == 136;

    let start = Instant::now();
    let algebra = data.full_algebra_audit();
    let algebra_ms = start.elapsed().as_millis();

    for _ in 0..warmup_runs {
        std::hint::black_box(data.full_algebra_audit());
    }
    let mut samples = Vec::with_capacity(measured_runs);
    for _ in 0..measured_runs {
        let start = Instant::now();
        std::hint::black_box(data.full_algebra_audit());
        samples.push(start.elapsed().as_micros());
    }
    samples.sort_unstable();
    let median = if samples.is_empty() {
        0
    } else {
        samples[samples.len() / 2]
    };
    let p95 = if samples.is_empty() {
        0
    } else {
        samples[((samples.len() as f64 * 0.95).ceil() as usize - 1).min(samples.len() - 1)]
    };
    let token_hash_matches = token_hash == PINNED_TOKEN_HASH;
    let raw_hash_matches = raw_hash == PINNED_RAW_JSON_SHA256;
    let passed = token_hash_matches
        && raw_hash_matches
        && data.n == 16
        && data.nb == 82
        && data.nf == 176
        && rust_generator_matches
        && algebra.bosonic_max_frobenius_residual < 1e-9;
    let conclusion = if passed {
        "The supplied artifact matches the pinned raw-byte and tolerance-snapped matrix-token hashes, the Rust generator matches every entry, and all 136 bosonic relations close exactly over Q(sqrt(2)). Both independent Python cross-checks agree with the Rust artifact. The paper/source inconsistencies remain subject to author confirmation."
    } else {
        "The supplied artifact failed at least one pinned reproduction check. It must not be reported as the validated 10D L/R artifact."
    };

    ReproductionAudit {
        schema_version: "tendim-reproduction-audit-v1",
        input_path: path.to_string(),
        paper_revision: "arXiv:2512.12157v1",
        paper_pdf_sha256: "4b3adbda34bf4ba870713ccddad285d8de70c5608fb53ec0dd6f6ae6dcfd4602",
        declared_upstream_repository: "https://github.com/mcmulaz/Super-Sym",
        declared_upstream_commit: UPSTREAM_COMMIT,
        declared_upstream_source_sha256: UPSTREAM_SOURCE_SHA256,
        raw_json_sha256_matches: raw_hash_matches,
        raw_json_sha256: raw_hash,
        canonical_matrix_token_hash_matches: token_hash_matches,
        canonical_matrix_token_hash: token_hash,
        canonical_token_tolerance: VALUE_TOL,
        rust_generator_entrywise_max_difference,
        rust_generator_exact_bosonic_pairs,
        rust_generator_matches,
        dimensions: DimensionsAudit {
            colors: data.n,
            bosons: data.nb,
            fermions: data.nf,
        },
        matrix_content: matrix_content_audit(&data),
        boson_order: boson_order(),
        fermion_order: fermion_order(),
        worked_examples_matching: example_matches,
        worked_examples_checked: examples.len(),
        worked_example_terms_matching: term_matches,
        worked_example_terms_checked: terms_checked,
        // Eq. (6.0.6) pins spinor label 16 to 16, while Eq. (6.0.5) would
        // require label 6 to map to 16. An injective fixed permutation cannot
        // satisfy both. The chi_9 examples give an independent contradiction.
        fixed_shared_spinor_label_permutation_reconciles_examples: false,
        worked_examples: examples,
        algebra,
        run_timings: TimingAudit {
            load_ms,
            content_validation_ms,
            algebra_ms,
            total_ms: total_start.elapsed().as_millis(),
        },
        algebra_benchmark: BenchmarkAudit {
            warmup_runs,
            measured_runs,
            median_microseconds: median,
            p95_microseconds: p95,
            build_profile: if cfg!(debug_assertions) {
                "debug"
            } else {
                "release"
            },
        },
        source_fidelity_basis: "The raw hash locks the serialized artifact. The token hash identifies its ordered symbolic values after snapping within 1e-9. Rust is the primary generator and verifies exact bosonic closure over Q(sqrt(2)). The NumPy and SymPy implementations are retained only as independent cross-checks. None executes Wolfram Language.",
        passed,
        conclusion: conclusion.to_string(),
    }
}

/// Tolerance for snapping a float entry to an exact symbolic token.
const VALUE_TOL: f64 = 1e-9;

/// sqrt(8) = 2*sqrt(2) (appears in L).
const SQRT8: f64 = 2.8284271247461903; // (2.0 * std::f64::consts::SQRT_2)
/// 1/sqrt(8) (appears in R).
const INV_SQRT8: f64 = 0.35355339059327373; // 1.0 / SQRT8

/// Map an L entry to its canonical token string, or None if it matches none.
fn l_token(v: f64) -> Option<&'static str> {
    // (value, token) table for L, EXACTLY the documented set { -2,-1,0,1,2,sqrt8 }.
    // The dataset uses only +sqrt8 (the Phi row); -sqrt8 is intentionally NOT
    // admitted so the validator matches the documented value set strictly.
    const TABLE: &[(f64, &str)] = &[
        (-2.0, "-2"),
        (-1.0, "-1"),
        (0.0, "0"),
        (1.0, "1"),
        (2.0, "2"),
        (SQRT8, "sqrt8"),
    ];
    snap(v, TABLE)
}

/// Map an R entry to its canonical token string, or None if it matches none.
fn r_token(v: f64) -> Option<&'static str> {
    // (value, token) table for R: { 0, +-1/16, +-1/8, +-7/16, +-1/2, +-1/sqrt8 }.
    const TABLE: &[(f64, &str)] = &[
        (0.0, "0"),
        (0.0625, "1/16"),
        (-0.0625, "-1/16"),
        (0.125, "1/8"),
        (-0.125, "-1/8"),
        (0.4375, "7/16"),
        (-0.4375, "-7/16"),
        (0.5, "1/2"),
        (-0.5, "-1/2"),
        (INV_SQRT8, "1/sqrt8"),
        (-INV_SQRT8, "-1/sqrt8"),
    ];
    snap(v, TABLE)
}

/// Find the token whose value is within `VALUE_TOL` of `v`.
fn snap(v: f64, table: &[(f64, &'static str)]) -> Option<&'static str> {
    for &(val, tok) in table {
        if (v - val).abs() <= VALUE_TOL {
            return Some(tok);
        }
    }
    None
}

/// Tolerances for [`verify_lift`] (Default: all 1e-9).
#[derive(Debug, Clone)]
pub struct LiftTolerances {
    pub bosonic: f64,
    pub entrywise: f64,
    pub partner: f64,
}
impl Default for LiftTolerances {
    fn default() -> Self {
        LiftTolerances {
            bosonic: 1e-9,
            entrywise: 1e-9,
            partner: 1e-9,
        }
    }
}

/// Outcome of [`verify_lift`].
#[derive(Debug, Clone)]
pub struct LiftVerification {
    pub shape_ok: bool,
    /// Candidate's own bosonic Garden residual (must be < tol.bosonic).
    pub bosonic_residual: f64,
    /// ENTRYWISE max |candidate - target| over every L and R entry (must be
    /// < tol.entrywise). Anchored entrywise, NOT per-pair Frobenius norm, which is
    /// orthogonally degenerate and admits false positives (adversarial review).
    pub max_lr_diff: f64,
    pub value_set_ok: bool,
    pub partner_ok: bool,
    /// Worst |L_I R_I − I_nb| entry over all I.
    pub partner_worst: f64,
    /// `Some(true/false)` when a `pinned_hash` was supplied; `None` otherwise.
    pub token_hash_match: Option<bool>,
    pub passed: bool,
}

/// Verify a candidate 10D lift against a reference `target` dataset: entrywise L/R
/// match, candidate bosonic Garden closure, value-set legality, the partner
/// relation `L_I R_I = I_nb`, and (optionally) the exact `canonical_token_hash`.
///
/// HONEST SCOPE (do not overclaim): with no lift PRODUCER yet, this is a REGRESSION
/// ORACLE. Exercised on the dataset's own L/R it certifies self-consistency of the
/// known 10D N=1 SUPERGRAVITY multiplet (82×176; NOT super-Yang-Mills, NOT
/// basis-independent). A pass means "entrywise-matches the pinned reference", never
/// "a new higher-dimensional multiplet was constructed or discovered". The token
/// hash pins only this dataset's specific basis/ordering.
pub fn verify_lift(
    candidate: &TenDimData,
    target: &TenDimData,
    tol: &LiftTolerances,
    pinned_hash: Option<&str>,
) -> LiftVerification {
    // Shape: counts AND per-matrix dims (nb×nf for L, nf×nb for R), so the
    // entrywise comparison below is index-safe and never panics.
    let dims_ok = |mats: &[Vec<Vec<f64>>], rows: usize, cols: usize| {
        mats.iter()
            .all(|m| m.len() == rows && m.iter().all(|row| row.len() == cols))
    };
    // Validate BOTH candidate and target dims (a caller may pass a malformed
    // target), so the entrywise zip below is always index-safe.
    let shape_ok = candidate.nb == target.nb
        && candidate.nf == target.nf
        && candidate.n == target.n
        && candidate.l.len() == target.l.len()
        && candidate.r.len() == target.r.len()
        && candidate.l.len() == candidate.n
        && candidate.r.len() == candidate.n
        && dims_ok(&candidate.l, candidate.nb, candidate.nf)
        && dims_ok(&candidate.r, candidate.nf, candidate.nb)
        && dims_ok(&target.l, target.nb, target.nf)
        && dims_ok(&target.r, target.nf, target.nb);
    if !shape_ok {
        return LiftVerification {
            shape_ok: false,
            bosonic_residual: f64::INFINITY,
            max_lr_diff: f64::INFINITY,
            value_set_ok: false,
            partner_ok: false,
            partner_worst: f64::INFINITY,
            token_hash_match: pinned_hash.map(|_| false),
            passed: false,
        };
    }

    let (bosonic_residual, _fermionic) = candidate.verify_garden();

    let mut max_lr_diff = 0.0f64;
    for i in 0..candidate.l.len() {
        for (a, b) in candidate.l[i]
            .iter()
            .flatten()
            .zip(target.l[i].iter().flatten())
        {
            max_lr_diff = max_lr_diff.max((a - b).abs());
        }
        for (a, b) in candidate.r[i]
            .iter()
            .flatten()
            .zip(target.r[i].iter().flatten())
        {
            max_lr_diff = max_lr_diff.max((a - b).abs());
        }
    }

    let value_set_ok = candidate.validate_value_sets().is_ok();

    // Partner relation L_I R_I = I_nb.
    let mut partner_worst = 0.0f64;
    for i in 0..candidate.n {
        let prod = matmul(&candidate.l[i], &candidate.r[i]); // nb×nb
        for (a, row) in prod.iter().enumerate() {
            for (b, &v) in row.iter().enumerate() {
                let want = if a == b { 1.0 } else { 0.0 };
                partner_worst = partner_worst.max((v - want).abs());
            }
        }
    }
    let partner_ok = partner_worst < tol.partner;

    // The token hash is exact-content; only meaningful (and only non-panicking)
    // when every entry snaps to a legal token, i.e. value_set_ok.
    let token_hash_match = match pinned_hash {
        Some(h) if value_set_ok => Some(candidate.canonical_token_hash() == h),
        Some(_) => Some(false), // illegal values -> cannot match the pinned hash
        None => None,
    };

    let passed = shape_ok
        && bosonic_residual < tol.bosonic
        && max_lr_diff < tol.entrywise
        && value_set_ok
        && partner_ok
        && token_hash_match != Some(false);

    LiftVerification {
        shape_ok,
        bosonic_residual,
        max_lr_diff,
        value_set_ok,
        partner_ok,
        partner_worst,
        token_hash_match,
        passed,
    }
}

/// Dense matrix multiply: (m x k) * (k x n) -> (m x n). Hand-rolled, no deps.
fn matmul(a: &[Vec<f64>], b: &[Vec<f64>]) -> Vec<Vec<f64>> {
    let m = a.len();
    let k = a[0].len();
    let n = b[0].len();
    debug_assert_eq!(b.len(), k, "inner dimensions must agree");
    let mut out = vec![vec![0.0_f64; n]; m];
    for i in 0..m {
        let a_row = &a[i];
        let out_row = &mut out[i];
        for p in 0..k {
            let aip = a_row[p];
            if aip == 0.0 {
                continue;
            }
            let b_row = &b[p];
            for j in 0..n {
                out_row[j] += aip * b_row[j];
            }
        }
    }
    out
}

/// Frobenius norm of `(x + y) - scale*I` for square `dim x dim` matrices.
fn frob_diff_minus_scaled_identity(x: &[Vec<f64>], y: &[Vec<f64>], scale: f64, dim: usize) -> f64 {
    let mut acc = 0.0_f64;
    for i in 0..dim {
        for j in 0..dim {
            let mut v = x[i][j] + y[i][j];
            if i == j {
                v -= scale;
            }
            acc += v * v;
        }
    }
    acc.sqrt()
}

/// Frobenius norm of E_IJ = (rilj + rjli)/2 - delta_IJ I.
fn e_remnant_norm(rilj: &[Vec<f64>], rjli: &[Vec<f64>], is_diag: bool, dim: usize) -> f64 {
    let mut acc = 0.0_f64;
    for i in 0..dim {
        for j in 0..dim {
            let mut e = 0.5 * (rilj[i][j] + rjli[i][j]);
            if is_diag && i == j {
                e -= 1.0;
            }
            acc += e * e;
        }
    }
    acc.sqrt()
}

// ---------------------------------------------------------------------------
// Vendored SHA-256 (FIPS 180-4). Self-contained, no external dependency, so the
// canonical token hash needs no new crate. Operates on a byte slice and returns
// the lowercase hex digest. Not constant-time (not needed: this hashes public
// matrix content for a content-lock, not secrets).
// ---------------------------------------------------------------------------
fn sha256_hex(input: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];

    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    // Pre-processing: padding.
    let bit_len = (input.len() as u64).wrapping_mul(8);
    let mut msg = input.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    // Process each 512-bit chunk.
    for chunk in msg.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (i, word) in chunk.chunks_exact(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let mut a = h[0];
        let mut b = h[1];
        let mut c = h[2];
        let mut d = h[3];
        let mut e = h[4];
        let mut f = h[5];
        let mut g = h[6];
        let mut hh = h[7];

        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);

            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }

        h[0] = h[0].wrapping_add(a);
        h[1] = h[1].wrapping_add(b);
        h[2] = h[2].wrapping_add(c);
        h[3] = h[3].wrapping_add(d);
        h[4] = h[4].wrapping_add(e);
        h[5] = h[5].wrapping_add(f);
        h[6] = h[6].wrapping_add(g);
        h[7] = h[7].wrapping_add(hh);
    }

    let mut out = String::with_capacity(64);
    for word in h {
        out.push_str(&format!("{word:08x}"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// verify_lift as a regression oracle: the dataset self-verifies (entrywise +
    /// hash), and any perturbation is rejected.
    #[test]
    fn verify_lift_self_and_perturbation() {
        const PINNED: &str = "4070fbeda9028cfd6c29097dfaf20df06300026e0c44d96e40c3d4b9a8faf244";
        let data = load(&dataset_path());
        let v = verify_lift(&data, &data, &LiftTolerances::default(), Some(PINNED));
        assert!(v.passed, "dataset must self-verify: {v:?}");
        assert_eq!(v.token_hash_match, Some(true));
        assert!(v.max_lr_diff == 0.0 && v.partner_ok && v.value_set_ok);

        // Perturb one L entry: breaks entrywise, value-set, bosonic, and hash.
        let mut bad = load(&dataset_path());
        bad.l[0][0][0] += 0.1;
        let vb = verify_lift(&bad, &data, &LiftTolerances::default(), Some(PINNED));
        assert!(!vb.passed, "perturbed candidate must be rejected: {vb:?}");
        assert!(
            vb.max_lr_diff > 1e-3,
            "entrywise diff should catch the perturbation"
        );
    }

    fn dataset_path() -> String {
        // Resolve relative to the crate root regardless of test cwd.
        format!("{}/data/tendim_10d_lr.json", env!("CARGO_MANIFEST_DIR"))
    }

    #[test]
    fn tendim_loads_with_expected_shapes() {
        let d = load(&dataset_path());
        assert_eq!(d.nb, 82);
        assert_eq!(d.nf, 176);
        assert_eq!(d.n, 16);
    }

    #[test]
    fn tendim_bosonic_garden_relation_holds() {
        let d = load(&dataset_path());
        let (bosonic_residual, fermionic_e_norm) = d.verify_garden();
        // Bosonic relation must close (allow tiny float noise).
        assert!(
            bosonic_residual < 1e-9,
            "bosonic Garden residual too large: {bosonic_residual}"
        );
        // Fermionic remnant E_IJ is the on-shell term: it must be nonzero,
        // confirming this is the genuine non-closing 10D representation.
        assert!(
            fermionic_e_norm > 1e-6,
            "expected nonzero fermionic E remnant, got {fermionic_e_norm}"
        );
    }

    /// Vendored SHA-256 sanity check against published FIPS-180-4 test vectors,
    /// so a hash regression is caught independently of the dataset.
    #[test]
    fn vendored_sha256_matches_known_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256_hex(b"The quick brown fox jumps over the lazy dog"),
            "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592"
        );
    }

    /// Full-quantity loader/verifier test: shapes, dof counts, value-set
    /// validation, bosonic closure, fermionic remnant (computed-here), a
    /// rank/partner sanity check, and the canonical-token hash lock.
    #[test]
    fn tendim_full_quantity_validation() {
        let d = load(&dataset_path());

        // --- Shapes: 16 generators; L is 82x176, R is 176x82. ---
        assert_eq!(d.n, 16, "expected 16 generators");
        assert_eq!(d.l.len(), 16);
        assert_eq!(d.r.len(), 16);
        for li in &d.l {
            assert_eq!(li.len(), 82, "each L matrix has 82 rows");
            assert!(
                li.iter().all(|row| row.len() == 176),
                "each L row has 176 cols"
            );
        }
        for ri in &d.r {
            assert_eq!(ri.len(), 176, "each R matrix has 176 rows");
            assert!(
                ri.iter().all(|row| row.len() == 82),
                "each R row has 82 cols"
            );
        }

        // --- DOF counts: nb=82=55+45+1-19, nf=176=160+16. ---
        assert_eq!(d.nb, 82, "boson dof");
        assert_eq!(d.nf, 176, "fermion dof");
        assert_eq!(55 + 45 + 1 - 19, 82, "boson dof decomposition");
        assert_eq!(160 + 16, 176, "fermion dof decomposition");

        // --- Strict allowed-value-set validation. ---
        d.validate_value_sets()
            .expect("all L/R entries must map to allowed symbolic tokens");

        // --- Bosonic residual must close; fermionic remnant computed here. ---
        let (bosonic_residual, fermionic_e_norm) = d.verify_garden();
        assert!(
            bosonic_residual < 1e-9,
            "bosonic Garden residual too large: {bosonic_residual}"
        );
        // NOTE: fermionic_e_norm is OUR COMPUTED on-shell remnant from this JSON,
        // NOT a paper-published number. We only assert it is nonzero (the algebra
        // closes only up to equations of motion) and report the value.
        assert!(
            fermionic_e_norm > 1e-6,
            "expected nonzero COMPUTED-HERE fermionic E remnant, got {fermionic_e_norm}"
        );
        eprintln!(
            "[tendim] COMPUTED-HERE max ||E_IJ|| (Frobenius) = {fermionic_e_norm} \
             (our remnant, not paper-reported); bosonic residual = {bosonic_residual}"
        );

        // --- Rank / partner sanity: R is the genuine GR-partner of L, not an
        // arbitrary matrix that happens to satisfy the bosonic side. No L_I and
        // no R_I may be the zero matrix (a trivial rank-deficient generator),
        // and every boson row of L_I must reach at least one fermion (no boson
        // is left without any partner coupling for generator I). ---
        for (gi, li) in d.l.iter().enumerate() {
            assert!(
                li.iter()
                    .any(|row| row.iter().any(|&x| x.abs() > VALUE_TOL)),
                "L[{gi}] is entirely zero (degenerate generator)"
            );
            for (rrow, row) in li.iter().enumerate() {
                assert!(
                    row.iter().any(|&x| x.abs() > VALUE_TOL),
                    "L[{gi}] boson row {rrow} has no fermion partner"
                );
            }
        }
        for (gi, ri) in d.r.iter().enumerate() {
            assert!(
                ri.iter()
                    .any(|row| row.iter().any(|&x| x.abs() > VALUE_TOL)),
                "R[{gi}] is entirely zero (degenerate generator)"
            );
        }
        // Diagonal-block partner relation (the strong partner test): for I==I
        // the bosonic product L_I R_I must equal I_82 (2 delta / 2), i.e. R_I is
        // a right-partner of L_I on the boson space.
        for gi in 0..d.n {
            let prod = matmul(&d.l[gi], &d.r[gi]); // 82x82, must be I_82
            let mut max_off = 0.0_f64;
            let mut min_diag = f64::INFINITY;
            for r in 0..d.nb {
                for c in 0..d.nb {
                    if r == c {
                        min_diag = min_diag.min(prod[r][c]);
                    } else {
                        max_off = max_off.max(prod[r][c].abs());
                    }
                }
            }
            assert!(
                max_off < 1e-9 && (min_diag - 1.0).abs() < 1e-9,
                "L[{gi}] R[{gi}] is not I_82 (max_off={max_off}, min_diag={min_diag})"
            );
        }

        // --- Hash lock: canonical token hash must equal the pinned constant. ---
        // Content-only: invariant to JSON metadata + float formatting.
        const PINNED_HASH: &str =
            "4070fbeda9028cfd6c29097dfaf20df06300026e0c44d96e40c3d4b9a8faf244";
        let h = d.canonical_token_hash();
        eprintln!("[tendim] canonical_token_hash = {h}");
        assert_eq!(
            h, PINNED_HASH,
            "canonical token hash drift: dataset CONTENT changed (pinned={PINNED_HASH}, got={h})"
        );
    }

    #[test]
    fn paper_worked_examples_are_compared_in_the_published_ordering() {
        let d = load(&dataset_path());
        let audit = worked_example_audit(&d);
        assert_eq!(audit.len(), 13);
        assert_eq!(audit.iter().filter(|x| x.direct_match).count(), 4);
        assert_eq!(audit.iter().filter(|x| x.support_match).count(), 7);
        assert_eq!(
            audit
                .iter()
                .map(|x| matching_term_count(&x.paper_terms, &x.regenerated_terms))
                .sum::<usize>(),
            7
        );
        assert_eq!(audit.iter().map(|x| x.paper_terms.len()).sum::<usize>(), 26);

        let h11 = audit.iter().find(|x| x.left_hand_side == "Q1 h11").unwrap();
        assert_eq!(h11.paper_terms, paper_terms(&[("psi1(6)", "2")]));
        assert_eq!(h11.regenerated_terms, paper_terms(&[("psi1(16)", "2")]));

        let psi = audit
            .iter()
            .find(|x| x.left_hand_side == "Q1 psi1(1)")
            .unwrap();
        assert_eq!(
            psi.paper_terms,
            paper_terms(&[("h19", "1/2"), ("B19", "1/16")])
        );
        assert_eq!(
            psi.regenerated_terms,
            paper_terms(&[("h19", "1/2"), ("B19", "-7/16")])
        );
    }

    #[test]
    fn complete_unordered_algebra_summary_is_stable() {
        let d = load(&dataset_path());
        let audit = d.full_algebra_audit();
        assert_eq!(audit.unordered_color_pairs_checked, 136);
        assert_eq!(audit.bosonic_relations_checked, 136);
        assert_eq!(audit.bosonic_scalar_equalities_checked, 914_464);
        assert!(audit.bosonic_max_frobenius_residual < 1e-9);
        assert_eq!(audit.fermionic_nonclosure_pairs, 136);
        assert_eq!(audit.fermionic_entries_examined_across_pairs, 4_212_736);
        assert_eq!(
            audit.fermionic_nonclosure_nonzero_entries_across_pairs,
            132_352
        );
        assert_eq!(audit.nonzero_threshold, 1e-9);
        assert!(
            (audit.fermionic_nonclosure_max_frobenius_norm - 9.924_716_620_639_604).abs() < 1e-12
        );
        assert_eq!(audit.fermionic_nonclosure_max_abs_entry, 1.0);
    }

    #[test]
    fn complete_matrix_content_counts_are_stable() {
        let d = load(&dataset_path());
        let audit = matrix_content_audit(&d);
        assert_eq!(audit.l_entries, 230_912);
        assert_eq!(audit.r_entries, 230_912);
        assert_eq!(audit.combined_entries, 461_824);
        assert_eq!(audit.l_nonzero_entries, 3_040);
        assert_eq!(audit.r_nonzero_entries, 7_648);
        assert_eq!(audit.l_nonzero_per_color, vec![190; 16]);
        assert_eq!(audit.r_nonzero_per_color, vec![478; 16]);
    }

    #[test]
    fn reproduction_status_passes_pinned_artifact_and_rejects_tampering() {
        let path = dataset_path();
        let report = reproduction_audit_with_benchmark(&path, 0, 0);
        assert!(report.passed);
        assert!(report.raw_json_sha256_matches);
        assert!(report.canonical_matrix_token_hash_matches);

        let original = std::fs::read_to_string(&path).unwrap();
        let changed = original.replacen("0.0", "1.0", 1);
        assert_ne!(changed, original);
        let temp = std::env::temp_dir().join(format!(
            "tendim-tampered-{}-{}.json",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));
        std::fs::write(&temp, changed).unwrap();
        let bad = reproduction_audit_with_benchmark(temp.to_str().unwrap(), 0, 0);
        std::fs::remove_file(&temp).unwrap();
        assert!(!bad.passed);
        assert!(!bad.raw_json_sha256_matches);
        assert!(
            !bad.canonical_matrix_token_hash_matches
                || bad.algebra.bosonic_max_frobenius_residual >= 1e-9
        );
    }

    #[test]
    fn field_order_matches_equation_6_0_7_and_upstream_source() {
        let bosons = boson_order();
        let fermions = fermion_order();
        assert_eq!(bosons.len(), 82);
        assert_eq!(&bosons[..4], ["h11", "h12", "h13", "h14"]);
        assert_eq!(
            &bosons[44..],
            [
                "h99", "B12", "B13", "B14", "B15", "B16", "B17", "B18", "B19", "B23", "B24", "B25",
                "B26", "B27", "B28", "B29", "B34", "B35", "B36", "B37", "B38", "B39", "B45", "B46",
                "B47", "B48", "B49", "B56", "B57", "B58", "B59", "B67", "B68", "B69", "B78", "B79",
                "B89", "phi"
            ]
        );
        assert_eq!(fermions.len(), 176);
        assert_eq!(fermions[0], "psi0(1)");
        assert_eq!(fermions[15], "psi0(16)");
        assert_eq!(fermions[16], "psi1(1)");
        assert_eq!(fermions[159], "psi9(16)");
        assert_eq!(fermions[160], "chi1");
        assert_eq!(fermions[175], "chi16");
    }
}
